import { ChampionsContentSideNavbarType } from '../../ContentSideNavbar/types';
export type TableDataType = 'TierTableData' | 'WinPickTableData' | 'BanTableData';
export interface TableData {
  tableDataType: TableDataType;
  championId: number;
}
export interface TierTableData extends TableData {
  tableDattableDataTypeaId: 'TierTableData';
  rankShift: number;
  winRate: string;
  pickRate: string;
}
export interface WinPickRateTableData extends TableData {
  tableDataType: 'WinPickTableData';
  winRate: string;
  pickRate: string;
}
export interface BanRateTableData extends TableData {
  tableDataType: 'BanTableData';
  banRate: string;
}
export interface ChampionRankTableProps {
  navItem: ChampionsContentSideNavbarType;
  tabItem: string;
}
export interface RankTableTierRowProps {
  tableData: TableData[];
  tabItem: string;
}
export const ChampionRankTableHeaderMap: Record<ChampionsContentSideNavbarType, string[]> = {
  티어: ['#', '', '챔피언', '승률', '픽률', '티어'],
  승률: ['#', '챔피언', '승률', '픽률'],
  픽률: ['#', '챔피언', '픽률', '승률'],
  벤률: ['#', '챔피언', '벤률'],
};
export const mockUpRankData: Record<ChampionsContentSideNavbarType, TableData[]> = {
  티어: [
    {
      rankShift: 2,
      championId: 107,
      winRate: '50.54%',
      pickRate: '52.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 81,
      winRate: '46.97%',
      pickRate: '50.51%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 28,
      winRate: '46.20%',
      pickRate: '48.60%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 54,
      winRate: '52.50%',
      pickRate: '47.61%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 32,
      winRate: '48.90%',
      pickRate: '46.74%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 87,
      winRate: '53.57%',
      pickRate: '48.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 55,
      winRate: '51.21%',
      pickRate: '50.82%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 2,
      winRate: '51.98%',
      pickRate: '51.71%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 24,
      winRate: '53.20%',
      pickRate: '46.23%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 96,
      winRate: '54.41%',
      pickRate: '52.43%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 44,
      winRate: '48.37%',
      pickRate: '51.06%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 127,
      winRate: '53.17%',
      pickRate: '48.52%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 25,
      winRate: '47.66%',
      pickRate: '54.70%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 78,
      winRate: '52.93%',
      pickRate: '52.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 134,
      winRate: '53.05%',
      pickRate: '51.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 144,
      winRate: '46.96%',
      pickRate: '54.49%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 112,
      winRate: '46.26%',
      pickRate: '48.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 104,
      winRate: '52.37%',
      pickRate: '50.35%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 141,
      winRate: '50.43%',
      pickRate: '49.02%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 46,
      winRate: '52.04%',
      pickRate: '46.12%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 109,
      winRate: '47.45%',
      pickRate: '51.27%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 38,
      winRate: '47.63%',
      pickRate: '51.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 33,
      winRate: '51.76%',
      pickRate: '48.59%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 61,
      winRate: '54.98%',
      pickRate: '51.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 84,
      winRate: '45.15%',
      pickRate: '54.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 86,
      winRate: '53.48%',
      pickRate: '47.12%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 74,
      winRate: '54.05%',
      pickRate: '53.70%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 10,
      winRate: '49.79%',
      pickRate: '48.97%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 29,
      winRate: '54.41%',
      pickRate: '54.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 21,
      winRate: '53.85%',
      pickRate: '51.96%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 58,
      winRate: '50.75%',
      pickRate: '53.63%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 124,
      winRate: '48.16%',
      pickRate: '51.28%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 149,
      winRate: '51.59%',
      pickRate: '45.98%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 37,
      winRate: '46.16%',
      pickRate: '54.46%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 66,
      winRate: '49.02%',
      pickRate: '50.67%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 40,
      winRate: '48.44%',
      pickRate: '53.06%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 19,
      winRate: '53.01%',
      pickRate: '54.64%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 125,
      winRate: '45.82%',
      pickRate: '46.05%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 115,
      winRate: '52.84%',
      pickRate: '53.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 110,
      winRate: '45.66%',
      pickRate: '45.86%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 123,
      winRate: '49.43%',
      pickRate: '48.19%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 72,
      winRate: '52.96%',
      pickRate: '45.66%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 151,
      winRate: '46.92%',
      pickRate: '49.57%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 105,
      winRate: '48.09%',
      pickRate: '53.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 67,
      winRate: '50.40%',
      pickRate: '48.98%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 136,
      winRate: '48.32%',
      pickRate: '49.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 1,
      winRate: '50.23%',
      pickRate: '51.47%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 59,
      winRate: '49.66%',
      pickRate: '47.64%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 122,
      winRate: '49.43%',
      pickRate: '51.43%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 26,
      winRate: '54.89%',
      pickRate: '51.19%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 71,
      winRate: '45.43%',
      pickRate: '53.83%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 16,
      winRate: '54.23%',
      pickRate: '54.23%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 63,
      winRate: '52.35%',
      pickRate: '52.03%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 108,
      winRate: '54.47%',
      pickRate: '54.08%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 140,
      winRate: '53.92%',
      pickRate: '51.28%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 27,
      winRate: '47.64%',
      pickRate: '50.08%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 15,
      winRate: '46.34%',
      pickRate: '47.23%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 6,
      winRate: '54.28%',
      pickRate: '46.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 34,
      winRate: '49.24%',
      pickRate: '48.83%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 126,
      winRate: '52.51%',
      pickRate: '52.74%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 121,
      winRate: '46.09%',
      pickRate: '45.98%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 102,
      winRate: '54.04%',
      pickRate: '54.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 47,
      winRate: '50.45%',
      pickRate: '51.88%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 116,
      winRate: '52.36%',
      pickRate: '50.39%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 147,
      winRate: '47.05%',
      pickRate: '49.67%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 11,
      winRate: '49.37%',
      pickRate: '45.93%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 9,
      winRate: '49.10%',
      pickRate: '50.64%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 65,
      winRate: '51.23%',
      pickRate: '46.63%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 82,
      winRate: '49.80%',
      pickRate: '54.11%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 51,
      winRate: '45.74%',
      pickRate: '51.54%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 18,
      winRate: '53.09%',
      pickRate: '52.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 138,
      winRate: '50.52%',
      pickRate: '45.72%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 14,
      winRate: '45.87%',
      pickRate: '47.72%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 17,
      winRate: '46.18%',
      pickRate: '49.29%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 22,
      winRate: '50.51%',
      pickRate: '50.71%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 83,
      winRate: '52.19%',
      pickRate: '54.47%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 20,
      winRate: '52.77%',
      pickRate: '54.34%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 113,
      winRate: '54.23%',
      pickRate: '45.14%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 130,
      winRate: '48.42%',
      pickRate: '45.44%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 70,
      winRate: '48.48%',
      pickRate: '47.82%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 77,
      winRate: '46.17%',
      pickRate: '50.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 150,
      winRate: '51.59%',
      pickRate: '46.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 137,
      winRate: '48.39%',
      pickRate: '52.70%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 39,
      winRate: '51.22%',
      pickRate: '54.61%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 139,
      winRate: '47.11%',
      pickRate: '46.24%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 92,
      winRate: '54.41%',
      pickRate: '45.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 68,
      winRate: '52.43%',
      pickRate: '48.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 45,
      winRate: '54.67%',
      pickRate: '53.35%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 119,
      winRate: '54.97%',
      pickRate: '50.25%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 69,
      winRate: '54.42%',
      pickRate: '54.18%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 23,
      winRate: '46.46%',
      pickRate: '47.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 42,
      winRate: '46.74%',
      pickRate: '51.71%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 50,
      winRate: '45.34%',
      pickRate: '45.73%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 97,
      winRate: '54.18%',
      pickRate: '46.08%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 49,
      winRate: '45.50%',
      pickRate: '50.01%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 93,
      winRate: '54.58%',
      pickRate: '47.91%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 57,
      winRate: '50.35%',
      pickRate: '46.66%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 143,
      winRate: '46.58%',
      pickRate: '46.53%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 94,
      winRate: '50.18%',
      pickRate: '49.39%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 128,
      winRate: '47.42%',
      pickRate: '50.87%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 148,
      winRate: '54.10%',
      pickRate: '45.54%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 145,
      winRate: '50.70%',
      pickRate: '49.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 43,
      winRate: '50.36%',
      pickRate: '53.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 53,
      winRate: '54.11%',
      pickRate: '47.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 142,
      winRate: '45.68%',
      pickRate: '51.82%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 101,
      winRate: '53.37%',
      pickRate: '53.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 79,
      winRate: '50.68%',
      pickRate: '52.47%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 111,
      winRate: '45.50%',
      pickRate: '46.73%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 13,
      winRate: '51.92%',
      pickRate: '54.18%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 73,
      winRate: '49.04%',
      pickRate: '50.97%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 131,
      winRate: '54.33%',
      pickRate: '47.25%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 5,
      winRate: '47.78%',
      pickRate: '49.83%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 129,
      winRate: '50.53%',
      pickRate: '53.56%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 52,
      winRate: '48.48%',
      pickRate: '52.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 60,
      winRate: '49.81%',
      pickRate: '52.30%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 7,
      winRate: '45.16%',
      pickRate: '46.68%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 62,
      winRate: '49.12%',
      pickRate: '46.88%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 76,
      winRate: '45.43%',
      pickRate: '47.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 99,
      winRate: '47.87%',
      pickRate: '50.16%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 80,
      winRate: '47.50%',
      pickRate: '45.89%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 106,
      winRate: '47.50%',
      pickRate: '48.12%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 133,
      winRate: '54.18%',
      pickRate: '47.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 4,
      winRate: '48.05%',
      pickRate: '46.33%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 89,
      winRate: '51.75%',
      pickRate: '52.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 103,
      winRate: '45.77%',
      pickRate: '45.45%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 98,
      winRate: '52.01%',
      pickRate: '52.56%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 146,
      winRate: '49.99%',
      pickRate: '47.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 30,
      winRate: '46.31%',
      pickRate: '46.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 35,
      winRate: '47.70%',
      pickRate: '48.37%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 88,
      winRate: '52.35%',
      pickRate: '46.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 12,
      winRate: '53.23%',
      pickRate: '45.12%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 90,
      winRate: '48.97%',
      pickRate: '54.45%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 95,
      winRate: '54.35%',
      pickRate: '53.97%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 31,
      winRate: '48.47%',
      pickRate: '45.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 85,
      winRate: '49.70%',
      pickRate: '46.29%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 56,
      winRate: '48.19%',
      pickRate: '47.07%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 135,
      winRate: '48.06%',
      pickRate: '52.53%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 3,
      winRate: '45.20%',
      pickRate: '47.73%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 120,
      winRate: '53.24%',
      pickRate: '48.74%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 75,
      winRate: '48.64%',
      pickRate: '54.40%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 114,
      winRate: '52.49%',
      pickRate: '54.76%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 64,
      winRate: '52.16%',
      pickRate: '51.28%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 118,
      winRate: '54.48%',
      pickRate: '45.11%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 8,
      winRate: '50.46%',
      pickRate: '49.69%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 117,
      winRate: '47.21%',
      pickRate: '52.81%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 132,
      winRate: '45.17%',
      pickRate: '46.11%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 36,
      winRate: '48.88%',
      pickRate: '47.94%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 91,
      winRate: '51.20%',
      pickRate: '54.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 48,
      winRate: '48.56%',
      pickRate: '50.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 100,
      winRate: '47.25%',
      pickRate: '54.09%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 41,
      winRate: '51.63%',
      pickRate: '47.83%',
      tableDataType: 'TierTableData',
    },
  ] as TierTableData[],
  승률: [
    {
      championId: 88,
      winRate: '46.86%',
      pickRate: '54.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 80,
      winRate: '46.56%',
      pickRate: '52.37%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 65,
      winRate: '53.84%',
      pickRate: '52.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 67,
      winRate: '47.19%',
      pickRate: '48.21%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 32,
      winRate: '45.30%',
      pickRate: '50.34%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 27,
      winRate: '52.66%',
      pickRate: '47.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 74,
      winRate: '45.48%',
      pickRate: '47.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 54,
      winRate: '46.80%',
      pickRate: '51.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 3,
      winRate: '45.31%',
      pickRate: '51.78%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 78,
      winRate: '54.57%',
      pickRate: '46.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 17,
      winRate: '53.51%',
      pickRate: '50.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 2,
      winRate: '54.06%',
      pickRate: '53.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 16,
      winRate: '50.49%',
      pickRate: '51.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 137,
      winRate: '47.86%',
      pickRate: '47.75%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 35,
      winRate: '51.43%',
      pickRate: '49.73%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 108,
      winRate: '47.21%',
      pickRate: '46.71%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 114,
      winRate: '48.12%',
      pickRate: '54.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 30,
      winRate: '49.80%',
      pickRate: '52.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 14,
      winRate: '48.66%',
      pickRate: '46.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 47,
      winRate: '49.17%',
      pickRate: '50.98%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 76,
      winRate: '47.99%',
      pickRate: '52.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 106,
      winRate: '45.07%',
      pickRate: '53.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 87,
      winRate: '46.78%',
      pickRate: '49.34%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 58,
      winRate: '49.51%',
      pickRate: '46.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 19,
      winRate: '45.32%',
      pickRate: '46.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 33,
      winRate: '50.07%',
      pickRate: '48.57%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 109,
      winRate: '50.74%',
      pickRate: '50.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 66,
      winRate: '50.08%',
      pickRate: '51.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 62,
      winRate: '46.57%',
      pickRate: '50.67%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 125,
      winRate: '49.92%',
      pickRate: '50.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 69,
      winRate: '45.56%',
      pickRate: '51.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 84,
      winRate: '53.11%',
      pickRate: '53.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 22,
      winRate: '45.87%',
      pickRate: '48.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 81,
      winRate: '48.99%',
      pickRate: '46.41%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 48,
      winRate: '49.98%',
      pickRate: '45.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 93,
      winRate: '52.41%',
      pickRate: '49.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 124,
      winRate: '47.47%',
      pickRate: '50.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 43,
      winRate: '47.90%',
      pickRate: '51.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 9,
      winRate: '53.97%',
      pickRate: '50.66%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 61,
      winRate: '46.47%',
      pickRate: '49.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 132,
      winRate: '50.55%',
      pickRate: '54.13%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 25,
      winRate: '47.09%',
      pickRate: '54.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 101,
      winRate: '54.36%',
      pickRate: '47.76%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 149,
      winRate: '47.64%',
      pickRate: '54.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 86,
      winRate: '51.49%',
      pickRate: '53.54%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 128,
      winRate: '54.92%',
      pickRate: '51.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 121,
      winRate: '54.94%',
      pickRate: '50.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 148,
      winRate: '54.28%',
      pickRate: '46.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 120,
      winRate: '50.30%',
      pickRate: '49.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 139,
      winRate: '53.04%',
      pickRate: '50.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 75,
      winRate: '54.69%',
      pickRate: '51.56%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 115,
      winRate: '54.35%',
      pickRate: '46.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 46,
      winRate: '49.39%',
      pickRate: '51.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 90,
      winRate: '50.88%',
      pickRate: '49.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 104,
      winRate: '45.75%',
      pickRate: '50.54%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 70,
      winRate: '50.97%',
      pickRate: '45.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 57,
      winRate: '54.67%',
      pickRate: '49.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 49,
      winRate: '52.40%',
      pickRate: '50.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 145,
      winRate: '49.70%',
      pickRate: '51.93%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 143,
      winRate: '47.42%',
      pickRate: '54.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 68,
      winRate: '47.33%',
      pickRate: '45.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 72,
      winRate: '48.95%',
      pickRate: '45.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 18,
      winRate: '45.61%',
      pickRate: '51.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 146,
      winRate: '54.86%',
      pickRate: '47.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 23,
      winRate: '49.66%',
      pickRate: '53.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 142,
      winRate: '52.39%',
      pickRate: '46.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 147,
      winRate: '48.62%',
      pickRate: '51.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 77,
      winRate: '48.25%',
      pickRate: '48.13%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 29,
      winRate: '45.89%',
      pickRate: '46.14%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 138,
      winRate: '54.22%',
      pickRate: '45.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 97,
      winRate: '45.77%',
      pickRate: '49.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 52,
      winRate: '46.06%',
      pickRate: '46.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 7,
      winRate: '47.12%',
      pickRate: '48.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 5,
      winRate: '45.41%',
      pickRate: '46.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 107,
      winRate: '45.76%',
      pickRate: '48.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 59,
      winRate: '45.81%',
      pickRate: '48.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 40,
      winRate: '49.20%',
      pickRate: '54.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 118,
      winRate: '52.30%',
      pickRate: '45.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 38,
      winRate: '54.54%',
      pickRate: '49.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 4,
      winRate: '53.39%',
      pickRate: '53.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 28,
      winRate: '52.16%',
      pickRate: '50.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 150,
      winRate: '54.41%',
      pickRate: '46.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 151,
      winRate: '54.47%',
      pickRate: '50.21%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 133,
      winRate: '52.98%',
      pickRate: '53.43%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 116,
      winRate: '50.23%',
      pickRate: '51.93%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 42,
      winRate: '47.80%',
      pickRate: '47.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 60,
      winRate: '53.55%',
      pickRate: '45.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 130,
      winRate: '46.80%',
      pickRate: '48.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 119,
      winRate: '46.86%',
      pickRate: '50.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 85,
      winRate: '49.34%',
      pickRate: '47.64%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 37,
      winRate: '47.51%',
      pickRate: '50.79%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 11,
      winRate: '46.95%',
      pickRate: '53.17%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 24,
      winRate: '54.33%',
      pickRate: '47.39%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 79,
      winRate: '45.41%',
      pickRate: '52.76%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 105,
      winRate: '49.19%',
      pickRate: '52.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 44,
      winRate: '53.42%',
      pickRate: '53.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 50,
      winRate: '53.95%',
      pickRate: '49.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 12,
      winRate: '49.59%',
      pickRate: '53.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 141,
      winRate: '46.84%',
      pickRate: '51.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 63,
      winRate: '52.98%',
      pickRate: '54.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 123,
      winRate: '54.31%',
      pickRate: '45.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 136,
      winRate: '52.87%',
      pickRate: '50.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 20,
      winRate: '48.85%',
      pickRate: '54.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 55,
      winRate: '46.48%',
      pickRate: '53.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 110,
      winRate: '54.29%',
      pickRate: '54.15%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 6,
      winRate: '52.89%',
      pickRate: '50.22%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 71,
      winRate: '51.71%',
      pickRate: '46.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 95,
      winRate: '48.67%',
      pickRate: '49.73%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 10,
      winRate: '45.16%',
      pickRate: '52.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 45,
      winRate: '50.05%',
      pickRate: '52.41%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 89,
      winRate: '47.66%',
      pickRate: '50.73%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 8,
      winRate: '46.90%',
      pickRate: '46.32%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 73,
      winRate: '54.82%',
      pickRate: '51.78%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 144,
      winRate: '48.62%',
      pickRate: '53.75%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 94,
      winRate: '52.48%',
      pickRate: '50.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 99,
      winRate: '52.02%',
      pickRate: '48.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 140,
      winRate: '47.94%',
      pickRate: '49.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 15,
      winRate: '47.47%',
      pickRate: '47.57%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 112,
      winRate: '54.77%',
      pickRate: '45.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 103,
      winRate: '52.66%',
      pickRate: '50.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 100,
      winRate: '51.95%',
      pickRate: '45.52%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 64,
      winRate: '52.90%',
      pickRate: '54.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 34,
      winRate: '53.70%',
      pickRate: '50.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 51,
      winRate: '47.05%',
      pickRate: '52.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 111,
      winRate: '53.94%',
      pickRate: '49.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 127,
      winRate: '51.93%',
      pickRate: '46.54%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 98,
      winRate: '45.62%',
      pickRate: '46.86%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 53,
      winRate: '51.43%',
      pickRate: '46.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 117,
      winRate: '53.26%',
      pickRate: '49.50%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 36,
      winRate: '46.68%',
      pickRate: '52.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 41,
      winRate: '48.02%',
      pickRate: '54.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 129,
      winRate: '54.75%',
      pickRate: '51.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 135,
      winRate: '53.87%',
      pickRate: '47.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 39,
      winRate: '46.55%',
      pickRate: '46.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 126,
      winRate: '47.18%',
      pickRate: '46.70%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 122,
      winRate: '49.71%',
      pickRate: '54.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 91,
      winRate: '51.99%',
      pickRate: '45.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 82,
      winRate: '47.72%',
      pickRate: '51.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 102,
      winRate: '52.89%',
      pickRate: '49.75%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 21,
      winRate: '54.02%',
      pickRate: '49.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 113,
      winRate: '48.01%',
      pickRate: '53.24%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 131,
      winRate: '54.73%',
      pickRate: '45.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 31,
      winRate: '49.61%',
      pickRate: '46.22%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 1,
      winRate: '49.81%',
      pickRate: '53.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 13,
      winRate: '54.83%',
      pickRate: '47.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 92,
      winRate: '51.67%',
      pickRate: '45.52%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 83,
      winRate: '49.73%',
      pickRate: '53.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 26,
      winRate: '45.51%',
      pickRate: '54.09%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 134,
      winRate: '54.02%',
      pickRate: '51.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 96,
      winRate: '47.12%',
      pickRate: '46.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 56,
      winRate: '47.32%',
      pickRate: '48.71%',
      tableDataType: 'WinPickTableData',
    },
  ] as WinPickRateTableData[],
  픽률: [
    {
      championId: 72,
      winRate: '49.17%',
      pickRate: '49.73%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 105,
      winRate: '45.28%',
      pickRate: '46.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 28,
      winRate: '50.89%',
      pickRate: '49.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 43,
      winRate: '53.13%',
      pickRate: '50.43%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 83,
      winRate: '50.59%',
      pickRate: '54.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 19,
      winRate: '48.49%',
      pickRate: '54.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 99,
      winRate: '45.72%',
      pickRate: '50.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 48,
      winRate: '47.09%',
      pickRate: '47.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 10,
      winRate: '50.82%',
      pickRate: '49.76%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 27,
      winRate: '51.19%',
      pickRate: '50.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 128,
      winRate: '51.65%',
      pickRate: '53.14%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 67,
      winRate: '46.27%',
      pickRate: '48.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 140,
      winRate: '46.05%',
      pickRate: '51.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 134,
      winRate: '49.32%',
      pickRate: '50.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 151,
      winRate: '47.13%',
      pickRate: '51.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 88,
      winRate: '53.69%',
      pickRate: '48.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 131,
      winRate: '47.67%',
      pickRate: '54.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 68,
      winRate: '50.12%',
      pickRate: '47.67%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 24,
      winRate: '50.22%',
      pickRate: '50.66%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 17,
      winRate: '51.31%',
      pickRate: '52.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 35,
      winRate: '48.52%',
      pickRate: '53.90%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 85,
      winRate: '52.03%',
      pickRate: '47.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 143,
      winRate: '48.84%',
      pickRate: '50.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 58,
      winRate: '50.61%',
      pickRate: '50.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 127,
      winRate: '53.68%',
      pickRate: '46.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 54,
      winRate: '52.42%',
      pickRate: '49.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 40,
      winRate: '52.16%',
      pickRate: '50.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 120,
      winRate: '47.91%',
      pickRate: '54.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 92,
      winRate: '47.75%',
      pickRate: '46.24%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 144,
      winRate: '48.68%',
      pickRate: '52.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 101,
      winRate: '51.79%',
      pickRate: '54.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 150,
      winRate: '49.43%',
      pickRate: '48.86%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 112,
      winRate: '45.45%',
      pickRate: '50.93%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 90,
      winRate: '54.30%',
      pickRate: '50.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 107,
      winRate: '48.96%',
      pickRate: '54.67%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 50,
      winRate: '49.22%',
      pickRate: '49.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 137,
      winRate: '50.54%',
      pickRate: '49.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 29,
      winRate: '47.83%',
      pickRate: '54.90%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 118,
      winRate: '48.06%',
      pickRate: '46.67%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 32,
      winRate: '54.32%',
      pickRate: '53.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 22,
      winRate: '49.00%',
      pickRate: '50.12%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 84,
      winRate: '52.23%',
      pickRate: '53.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 133,
      winRate: '52.86%',
      pickRate: '47.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 20,
      winRate: '50.25%',
      pickRate: '49.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 62,
      winRate: '45.71%',
      pickRate: '46.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 25,
      winRate: '48.05%',
      pickRate: '50.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 97,
      winRate: '48.20%',
      pickRate: '53.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 149,
      winRate: '47.14%',
      pickRate: '51.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 103,
      winRate: '46.60%',
      pickRate: '48.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 74,
      winRate: '53.48%',
      pickRate: '51.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 100,
      winRate: '46.24%',
      pickRate: '54.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 1,
      winRate: '45.17%',
      pickRate: '52.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 142,
      winRate: '45.09%',
      pickRate: '46.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 15,
      winRate: '45.14%',
      pickRate: '50.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 124,
      winRate: '54.00%',
      pickRate: '51.17%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 82,
      winRate: '50.11%',
      pickRate: '54.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 57,
      winRate: '52.15%',
      pickRate: '46.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 76,
      winRate: '54.39%',
      pickRate: '47.78%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 71,
      winRate: '46.96%',
      pickRate: '54.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 23,
      winRate: '45.96%',
      pickRate: '46.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 5,
      winRate: '50.21%',
      pickRate: '53.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 78,
      winRate: '45.96%',
      pickRate: '47.50%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 126,
      winRate: '45.99%',
      pickRate: '48.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 129,
      winRate: '51.20%',
      pickRate: '45.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 123,
      winRate: '46.40%',
      pickRate: '50.93%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 132,
      winRate: '46.56%',
      pickRate: '47.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 38,
      winRate: '49.07%',
      pickRate: '54.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 95,
      winRate: '50.79%',
      pickRate: '47.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 9,
      winRate: '54.11%',
      pickRate: '45.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 33,
      winRate: '54.02%',
      pickRate: '52.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 145,
      winRate: '50.25%',
      pickRate: '51.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 18,
      winRate: '52.54%',
      pickRate: '45.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 49,
      winRate: '54.20%',
      pickRate: '46.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 119,
      winRate: '50.74%',
      pickRate: '47.13%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 8,
      winRate: '53.90%',
      pickRate: '47.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 98,
      winRate: '46.28%',
      pickRate: '54.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 53,
      winRate: '48.30%',
      pickRate: '53.27%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 37,
      winRate: '47.56%',
      pickRate: '47.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 51,
      winRate: '50.07%',
      pickRate: '49.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 122,
      winRate: '49.55%',
      pickRate: '46.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 130,
      winRate: '54.41%',
      pickRate: '46.22%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 110,
      winRate: '46.87%',
      pickRate: '53.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 61,
      winRate: '53.51%',
      pickRate: '51.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 42,
      winRate: '54.26%',
      pickRate: '51.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 55,
      winRate: '50.18%',
      pickRate: '48.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 13,
      winRate: '49.59%',
      pickRate: '48.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 44,
      winRate: '54.46%',
      pickRate: '50.71%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 41,
      winRate: '48.67%',
      pickRate: '50.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 146,
      winRate: '54.79%',
      pickRate: '46.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 16,
      winRate: '48.07%',
      pickRate: '45.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 147,
      winRate: '53.99%',
      pickRate: '47.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 2,
      winRate: '53.93%',
      pickRate: '50.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 113,
      winRate: '45.42%',
      pickRate: '46.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 79,
      winRate: '48.31%',
      pickRate: '54.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 60,
      winRate: '45.53%',
      pickRate: '53.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 3,
      winRate: '53.63%',
      pickRate: '52.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 96,
      winRate: '50.58%',
      pickRate: '54.56%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 64,
      winRate: '46.73%',
      pickRate: '45.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 102,
      winRate: '47.83%',
      pickRate: '53.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 148,
      winRate: '52.17%',
      pickRate: '50.43%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 114,
      winRate: '52.41%',
      pickRate: '47.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 12,
      winRate: '48.24%',
      pickRate: '49.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 108,
      winRate: '53.78%',
      pickRate: '46.11%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 26,
      winRate: '53.87%',
      pickRate: '53.64%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 59,
      winRate: '48.59%',
      pickRate: '50.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 73,
      winRate: '49.26%',
      pickRate: '52.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 34,
      winRate: '48.77%',
      pickRate: '50.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 86,
      winRate: '49.69%',
      pickRate: '50.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 69,
      winRate: '50.12%',
      pickRate: '51.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 91,
      winRate: '52.95%',
      pickRate: '50.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 7,
      winRate: '53.11%',
      pickRate: '52.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 6,
      winRate: '51.66%',
      pickRate: '47.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 65,
      winRate: '48.80%',
      pickRate: '45.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 115,
      winRate: '46.80%',
      pickRate: '54.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 93,
      winRate: '49.80%',
      pickRate: '53.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 136,
      winRate: '48.38%',
      pickRate: '49.56%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 45,
      winRate: '52.06%',
      pickRate: '50.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 31,
      winRate: '47.45%',
      pickRate: '53.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 109,
      winRate: '50.42%',
      pickRate: '50.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 117,
      winRate: '51.30%',
      pickRate: '52.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 47,
      winRate: '45.73%',
      pickRate: '51.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 80,
      winRate: '50.25%',
      pickRate: '50.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 106,
      winRate: '54.07%',
      pickRate: '45.08%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 11,
      winRate: '54.36%',
      pickRate: '45.71%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 139,
      winRate: '47.88%',
      pickRate: '47.09%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 4,
      winRate: '50.40%',
      pickRate: '45.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 46,
      winRate: '47.71%',
      pickRate: '51.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 66,
      winRate: '45.25%',
      pickRate: '52.12%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 141,
      winRate: '52.90%',
      pickRate: '48.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 63,
      winRate: '47.45%',
      pickRate: '52.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 138,
      winRate: '54.40%',
      pickRate: '49.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 21,
      winRate: '50.89%',
      pickRate: '47.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 89,
      winRate: '48.69%',
      pickRate: '53.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 70,
      winRate: '49.48%',
      pickRate: '49.39%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 77,
      winRate: '54.85%',
      pickRate: '49.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 111,
      winRate: '49.88%',
      pickRate: '47.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 56,
      winRate: '53.72%',
      pickRate: '48.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 125,
      winRate: '53.22%',
      pickRate: '47.15%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 94,
      winRate: '45.52%',
      pickRate: '52.27%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 75,
      winRate: '48.73%',
      pickRate: '48.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 135,
      winRate: '54.65%',
      pickRate: '46.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 121,
      winRate: '48.09%',
      pickRate: '54.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 39,
      winRate: '47.25%',
      pickRate: '46.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 52,
      winRate: '52.74%',
      pickRate: '54.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 116,
      winRate: '48.81%',
      pickRate: '51.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 104,
      winRate: '48.73%',
      pickRate: '51.33%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 30,
      winRate: '54.97%',
      pickRate: '46.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 81,
      winRate: '54.73%',
      pickRate: '48.08%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 87,
      winRate: '47.47%',
      pickRate: '48.98%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 36,
      winRate: '47.95%',
      pickRate: '52.76%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 14,
      winRate: '46.14%',
      pickRate: '51.04%',
      tableDataType: 'WinPickTableData',
    },
  ] as WinPickRateTableData[],
  벤률: [
    {
      championId: 47,
      banRate: '47.88%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 56,
      banRate: '51.85%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 141,
      banRate: '45.37%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 79,
      banRate: '48.72%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 106,
      banRate: '49.34%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 71,
      banRate: '53.40%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 30,
      banRate: '47.14%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 59,
      banRate: '54.86%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 52,
      banRate: '53.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 88,
      banRate: '45.12%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 38,
      banRate: '45.80%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 81,
      banRate: '47.87%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 9,
      banRate: '47.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 15,
      banRate: '51.52%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 98,
      banRate: '45.46%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 124,
      banRate: '54.07%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 82,
      banRate: '48.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 17,
      banRate: '46.20%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 102,
      banRate: '50.50%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 78,
      banRate: '46.56%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 42,
      banRate: '53.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 62,
      banRate: '54.62%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 25,
      banRate: '47.55%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 35,
      banRate: '50.66%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 22,
      banRate: '45.70%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 144,
      banRate: '48.05%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 29,
      banRate: '47.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 86,
      banRate: '51.22%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 118,
      banRate: '53.81%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 27,
      banRate: '53.80%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 101,
      banRate: '45.24%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 72,
      banRate: '45.58%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 110,
      banRate: '51.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 117,
      banRate: '48.13%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 13,
      banRate: '49.62%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 94,
      banRate: '46.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 85,
      banRate: '53.40%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 149,
      banRate: '46.27%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 135,
      banRate: '51.06%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 60,
      banRate: '52.52%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 136,
      banRate: '53.48%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 150,
      banRate: '46.24%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 105,
      banRate: '53.82%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 132,
      banRate: '47.66%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 121,
      banRate: '47.64%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 6,
      banRate: '47.18%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 3,
      banRate: '52.43%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 143,
      banRate: '51.26%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 23,
      banRate: '50.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 11,
      banRate: '45.89%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 19,
      banRate: '49.40%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 131,
      banRate: '50.95%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 26,
      banRate: '50.13%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 113,
      banRate: '49.83%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 16,
      banRate: '50.84%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 58,
      banRate: '45.06%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 10,
      banRate: '45.65%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 76,
      banRate: '54.83%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 90,
      banRate: '50.77%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 119,
      banRate: '48.99%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 39,
      banRate: '46.32%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 122,
      banRate: '54.42%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 5,
      banRate: '47.06%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 120,
      banRate: '47.67%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 68,
      banRate: '49.70%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 70,
      banRate: '52.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 126,
      banRate: '52.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 128,
      banRate: '46.19%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 133,
      banRate: '53.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 12,
      banRate: '53.56%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 44,
      banRate: '50.84%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 55,
      banRate: '50.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 24,
      banRate: '52.95%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 20,
      banRate: '54.99%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 129,
      banRate: '48.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 51,
      banRate: '52.69%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 83,
      banRate: '47.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 53,
      banRate: '48.93%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 2,
      banRate: '45.24%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 123,
      banRate: '54.11%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 134,
      banRate: '46.81%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 67,
      banRate: '45.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 112,
      banRate: '48.90%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 139,
      banRate: '47.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 145,
      banRate: '54.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 99,
      banRate: '48.82%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 41,
      banRate: '51.22%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 142,
      banRate: '50.27%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 75,
      banRate: '51.53%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 46,
      banRate: '51.92%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 97,
      banRate: '49.18%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 96,
      banRate: '49.43%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 1,
      banRate: '49.32%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 40,
      banRate: '45.51%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 48,
      banRate: '52.15%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 138,
      banRate: '52.53%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 36,
      banRate: '53.47%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 8,
      banRate: '54.95%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 87,
      banRate: '54.25%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 32,
      banRate: '49.05%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 63,
      banRate: '51.15%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 107,
      banRate: '53.00%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 49,
      banRate: '48.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 115,
      banRate: '49.63%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 127,
      banRate: '51.48%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 92,
      banRate: '48.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 66,
      banRate: '45.11%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 54,
      banRate: '50.93%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 148,
      banRate: '53.12%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 109,
      banRate: '45.71%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 7,
      banRate: '48.39%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 43,
      banRate: '47.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 111,
      banRate: '53.77%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 28,
      banRate: '45.95%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 4,
      banRate: '45.25%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 91,
      banRate: '54.61%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 80,
      banRate: '49.20%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 34,
      banRate: '54.13%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 104,
      banRate: '45.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 146,
      banRate: '51.67%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 73,
      banRate: '45.27%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 64,
      banRate: '51.05%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 84,
      banRate: '51.07%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 18,
      banRate: '49.30%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 130,
      banRate: '47.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 65,
      banRate: '50.65%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 37,
      banRate: '47.03%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 137,
      banRate: '47.00%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 151,
      banRate: '51.85%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 77,
      banRate: '52.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 74,
      banRate: '45.52%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 61,
      banRate: '49.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 93,
      banRate: '53.57%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 57,
      banRate: '53.69%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 116,
      banRate: '45.17%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 45,
      banRate: '54.44%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 95,
      banRate: '47.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 31,
      banRate: '45.06%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 89,
      banRate: '54.57%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 108,
      banRate: '51.04%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 103,
      banRate: '54.38%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 21,
      banRate: '53.35%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 14,
      banRate: '51.50%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 114,
      banRate: '47.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 147,
      banRate: '54.74%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 50,
      banRate: '48.28%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 125,
      banRate: '47.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 33,
      banRate: '47.11%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 100,
      banRate: '53.43%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 69,
      banRate: '47.22%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 140,
      banRate: '45.31%',
      tableDataType: 'BanTableData',
    },
  ] as BanRateTableData[],
};
