import { ChampionsContentSideNavbarType } from '../../ContentSideNavbar/types';
export type TableDataType = 'TierTableData' | 'WinPickTableData' | 'BanTableData';
export interface TableData {
  tableDataType: TableDataType;
  championId: number;
}
export interface TierTableData extends TableData {
  tableDattableDataTypeaId: 'TierTableData';
  rankShift: number;
  winRate: string;
  pickRate: string;
}
export interface WinPickRateTableData extends TableData {
  tableDataType: 'WinPickTableData';
  winRate: string;
  pickRate: string;
}
export interface BanRateTableData extends TableData {
  tableDataType: 'BanTableData';
  banRate: string;
}
export interface ChampionRankTableProps {
  navItem: ChampionsContentSideNavbarType;
  tabItem: string;
}
export interface RankTableTierRowProps {
  tableData: TableData[];
  tabItem: string;
}
export const ChampionRankTableHeaderMap: Record<ChampionsContentSideNavbarType, string[]> = {
  티어: ['#', '', '챔피언', '승률', '픽률', '티어'],
  승률: ['#', '챔피언', '승률', '픽률'],
  픽률: ['#', '챔피언', '픽률', '승률'],
  벤률: ['#', '챔피언', '벤률'],
};
export const mockUpRotationChampionId: number[] = [
  2,
  3,
  5,
  31,
  50,
  89,
  105,
  119,
  127,
  154,
  163,
  235,
  266,
  517,
  523,
];
export const mockUpRankData: Record<ChampionsContentSideNavbarType, TableData[]> = {
  티어: [
    {
      rankShift: 4,
      championId: 80,
      winRate: '49.02%',
      pickRate: '53.65%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 268,
      winRate: '47.48%',
      pickRate: '46.68%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 59,
      winRate: '48.37%',
      pickRate: '53.61%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 119,
      winRate: '48.12%',
      pickRate: '52.85%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 53,
      winRate: '48.32%',
      pickRate: '52.33%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 25,
      winRate: '50.69%',
      pickRate: '53.45%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 57,
      winRate: '45.18%',
      pickRate: '54.27%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 246,
      winRate: '53.90%',
      pickRate: '49.89%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 85,
      winRate: '50.42%',
      pickRate: '50.69%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 1,
      winRate: '47.86%',
      pickRate: '48.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 110,
      winRate: '50.48%',
      pickRate: '46.54%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 427,
      winRate: '54.11%',
      pickRate: '47.99%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 5,
      winRate: '46.46%',
      pickRate: '45.21%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 82,
      winRate: '50.35%',
      pickRate: '50.46%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 497,
      winRate: '47.27%',
      pickRate: '52.15%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 101,
      winRate: '48.32%',
      pickRate: '46.64%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 516,
      winRate: '50.61%',
      pickRate: '52.64%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 92,
      winRate: '54.23%',
      pickRate: '49.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 145,
      winRate: '53.26%',
      pickRate: '51.21%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 420,
      winRate: '52.68%',
      pickRate: '53.48%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 234,
      winRate: '46.11%',
      pickRate: '49.69%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 4,
      winRate: '48.92%',
      pickRate: '47.66%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 24,
      winRate: '48.31%',
      pickRate: '47.02%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 48,
      winRate: '47.70%',
      pickRate: '46.75%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 90,
      winRate: '46.09%',
      pickRate: '54.34%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 254,
      winRate: '53.80%',
      pickRate: '46.05%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 421,
      winRate: '52.93%',
      pickRate: '51.68%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 163,
      winRate: '49.88%',
      pickRate: '52.88%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 161,
      winRate: '51.26%',
      pickRate: '54.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 30,
      winRate: '46.73%',
      pickRate: '50.01%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 120,
      winRate: '51.16%',
      pickRate: '48.46%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 112,
      winRate: '51.47%',
      pickRate: '51.42%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 29,
      winRate: '48.13%',
      pickRate: '47.42%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 32,
      winRate: '45.41%',
      pickRate: '48.39%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 157,
      winRate: '46.92%',
      pickRate: '54.87%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 432,
      winRate: '54.61%',
      pickRate: '45.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 412,
      winRate: '47.45%',
      pickRate: '48.31%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 76,
      winRate: '50.15%',
      pickRate: '46.68%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 105,
      winRate: '52.99%',
      pickRate: '51.39%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 62,
      winRate: '46.52%',
      pickRate: '46.50%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 98,
      winRate: '45.40%',
      pickRate: '53.20%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 19,
      winRate: '54.08%',
      pickRate: '52.09%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 150,
      winRate: '50.98%',
      pickRate: '49.23%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 16,
      winRate: '52.39%',
      pickRate: '52.94%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 201,
      winRate: '48.30%',
      pickRate: '48.76%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 31,
      winRate: '48.43%',
      pickRate: '50.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 223,
      winRate: '49.51%',
      pickRate: '54.50%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 38,
      winRate: '52.21%',
      pickRate: '50.52%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 2,
      winRate: '52.82%',
      pickRate: '45.69%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 21,
      winRate: '52.37%',
      pickRate: '46.74%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 203,
      winRate: '46.88%',
      pickRate: '51.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 45,
      winRate: '45.74%',
      pickRate: '49.01%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 350,
      winRate: '47.34%',
      pickRate: '45.28%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 7,
      winRate: '51.53%',
      pickRate: '49.11%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 39,
      winRate: '52.30%',
      pickRate: '52.98%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 115,
      winRate: '46.83%',
      pickRate: '52.41%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 245,
      winRate: '45.71%',
      pickRate: '53.70%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 142,
      winRate: '46.39%',
      pickRate: '53.19%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 50,
      winRate: '46.78%',
      pickRate: '45.84%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 107,
      winRate: '47.08%',
      pickRate: '51.29%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 517,
      winRate: '50.40%',
      pickRate: '49.58%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 13,
      winRate: '49.18%',
      pickRate: '45.56%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 222,
      winRate: '48.47%',
      pickRate: '52.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 111,
      winRate: '52.16%',
      pickRate: '50.98%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 28,
      winRate: '48.14%',
      pickRate: '48.37%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 68,
      winRate: '45.15%',
      pickRate: '50.77%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 36,
      winRate: '49.62%',
      pickRate: '45.36%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 34,
      winRate: '49.01%',
      pickRate: '50.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 518,
      winRate: '46.19%',
      pickRate: '48.75%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 67,
      winRate: '47.87%',
      pickRate: '45.99%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 164,
      winRate: '52.59%',
      pickRate: '50.88%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 143,
      winRate: '49.08%',
      pickRate: '45.02%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 117,
      winRate: '50.72%',
      pickRate: '49.31%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 91,
      winRate: '52.86%',
      pickRate: '52.66%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 526,
      winRate: '45.53%',
      pickRate: '48.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 18,
      winRate: '47.09%',
      pickRate: '47.82%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 26,
      winRate: '52.22%',
      pickRate: '52.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 126,
      winRate: '51.52%',
      pickRate: '51.26%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 122,
      winRate: '50.42%',
      pickRate: '54.94%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 360,
      winRate: '53.36%',
      pickRate: '45.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 121,
      winRate: '50.34%',
      pickRate: '53.86%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 267,
      winRate: '47.66%',
      pickRate: '49.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 523,
      winRate: '45.17%',
      pickRate: '52.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 54,
      winRate: '50.52%',
      pickRate: '51.45%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 56,
      winRate: '49.06%',
      pickRate: '46.63%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 14,
      winRate: '52.53%',
      pickRate: '46.11%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 133,
      winRate: '49.05%',
      pickRate: '51.59%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 27,
      winRate: '48.42%',
      pickRate: '52.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 136,
      winRate: '50.73%',
      pickRate: '46.14%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 83,
      winRate: '50.80%',
      pickRate: '46.45%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 20,
      winRate: '51.94%',
      pickRate: '48.52%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 96,
      winRate: '48.86%',
      pickRate: '47.23%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 72,
      winRate: '51.35%',
      pickRate: '49.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 134,
      winRate: '52.96%',
      pickRate: '46.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 81,
      winRate: '54.23%',
      pickRate: '45.83%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 154,
      winRate: '45.88%',
      pickRate: '54.48%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 33,
      winRate: '51.22%',
      pickRate: '47.44%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 35,
      winRate: '48.55%',
      pickRate: '53.54%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 75,
      winRate: '45.78%',
      pickRate: '47.49%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 22,
      winRate: '48.71%',
      pickRate: '50.03%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 89,
      winRate: '48.65%',
      pickRate: '54.56%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 876,
      winRate: '46.00%',
      pickRate: '48.02%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 42,
      winRate: '52.35%',
      pickRate: '50.65%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 235,
      winRate: '46.37%',
      pickRate: '48.02%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 58,
      winRate: '54.75%',
      pickRate: '52.99%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 11,
      winRate: '46.78%',
      pickRate: '48.94%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 64,
      winRate: '48.48%',
      pickRate: '52.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 10,
      winRate: '53.71%',
      pickRate: '50.57%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 84,
      winRate: '53.27%',
      pickRate: '45.81%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 44,
      winRate: '51.19%',
      pickRate: '45.87%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 131,
      winRate: '52.56%',
      pickRate: '52.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 777,
      winRate: '54.25%',
      pickRate: '50.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 103,
      winRate: '48.91%',
      pickRate: '53.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 86,
      winRate: '48.95%',
      pickRate: '49.56%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 240,
      winRate: '46.45%',
      pickRate: '48.41%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 106,
      winRate: '51.55%',
      pickRate: '53.21%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 60,
      winRate: '47.79%',
      pickRate: '49.05%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 37,
      winRate: '48.86%',
      pickRate: '46.29%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 43,
      winRate: '49.86%',
      pickRate: '54.74%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 61,
      winRate: '54.84%',
      pickRate: '52.60%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 141,
      winRate: '45.65%',
      pickRate: '48.07%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 266,
      winRate: '52.88%',
      pickRate: '51.25%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 113,
      winRate: '50.65%',
      pickRate: '52.34%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 40,
      winRate: '52.42%',
      pickRate: '46.62%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 9,
      winRate: '52.01%',
      pickRate: '51.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 55,
      winRate: '47.00%',
      pickRate: '53.36%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 8,
      winRate: '48.14%',
      pickRate: '53.70%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 15,
      winRate: '47.39%',
      pickRate: '47.10%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 79,
      winRate: '47.42%',
      pickRate: '49.65%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 12,
      winRate: '52.96%',
      pickRate: '52.51%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 3,
      winRate: '48.17%',
      pickRate: '54.81%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 202,
      winRate: '53.77%',
      pickRate: '52.16%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -1,
      championId: 74,
      winRate: '52.50%',
      pickRate: '48.26%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 429,
      winRate: '48.68%',
      pickRate: '51.07%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 6,
      winRate: '49.22%',
      pickRate: '45.72%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -4,
      championId: 104,
      winRate: '47.55%',
      pickRate: '53.73%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 238,
      winRate: '47.36%',
      pickRate: '48.57%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 1,
      championId: 23,
      winRate: '48.94%',
      pickRate: '47.86%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 51,
      winRate: '49.32%',
      pickRate: '51.20%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 3,
      championId: 127,
      winRate: '46.26%',
      pickRate: '52.69%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 555,
      winRate: '47.85%',
      pickRate: '48.78%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 78,
      winRate: '46.84%',
      pickRate: '45.13%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 498,
      winRate: '49.85%',
      pickRate: '47.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 102,
      winRate: '54.13%',
      pickRate: '52.93%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -3,
      championId: 99,
      winRate: '45.32%',
      pickRate: '54.60%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 63,
      winRate: '51.39%',
      pickRate: '50.76%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 114,
      winRate: '47.80%',
      pickRate: '54.00%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 41,
      winRate: '50.20%',
      pickRate: '52.04%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 77,
      winRate: '47.69%',
      pickRate: '45.55%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 0,
      championId: 147,
      winRate: '46.73%',
      pickRate: '51.17%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 4,
      championId: 236,
      winRate: '50.85%',
      pickRate: '52.92%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: 2,
      championId: 69,
      winRate: '53.49%',
      pickRate: '53.48%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -2,
      championId: 17,
      winRate: '53.43%',
      pickRate: '46.47%',
      tableDataType: 'TierTableData',
    },
    {
      rankShift: -5,
      championId: 875,
      winRate: '51.13%',
      pickRate: '53.60%',
      tableDataType: 'TierTableData',
    },
  ] as TierTableData[],
  승률: [
    {
      championId: 420,
      winRate: '53.44%',
      pickRate: '49.05%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 10,
      winRate: '49.75%',
      pickRate: '49.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 9,
      winRate: '51.85%',
      pickRate: '48.71%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 61,
      winRate: '45.80%',
      pickRate: '51.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 102,
      winRate: '47.51%',
      pickRate: '50.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 89,
      winRate: '50.36%',
      pickRate: '50.98%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 15,
      winRate: '49.77%',
      pickRate: '53.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 21,
      winRate: '46.36%',
      pickRate: '53.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 75,
      winRate: '53.04%',
      pickRate: '49.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 67,
      winRate: '53.22%',
      pickRate: '50.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 875,
      winRate: '50.87%',
      pickRate: '49.24%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 14,
      winRate: '45.66%',
      pickRate: '46.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 24,
      winRate: '52.05%',
      pickRate: '45.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 2,
      winRate: '45.48%',
      pickRate: '50.50%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 154,
      winRate: '47.90%',
      pickRate: '53.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 131,
      winRate: '47.26%',
      pickRate: '49.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 112,
      winRate: '48.00%',
      pickRate: '48.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 147,
      winRate: '50.90%',
      pickRate: '53.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 23,
      winRate: '48.75%',
      pickRate: '46.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 28,
      winRate: '47.00%',
      pickRate: '51.79%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 90,
      winRate: '49.76%',
      pickRate: '45.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 99,
      winRate: '52.23%',
      pickRate: '54.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 80,
      winRate: '51.56%',
      pickRate: '53.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 234,
      winRate: '46.61%',
      pickRate: '51.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 43,
      winRate: '53.99%',
      pickRate: '50.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 18,
      winRate: '46.59%',
      pickRate: '45.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 119,
      winRate: '46.32%',
      pickRate: '45.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 267,
      winRate: '51.43%',
      pickRate: '50.12%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 79,
      winRate: '49.15%',
      pickRate: '52.34%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 432,
      winRate: '54.01%',
      pickRate: '54.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 54,
      winRate: '47.84%',
      pickRate: '50.56%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 145,
      winRate: '46.95%',
      pickRate: '54.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 201,
      winRate: '51.37%',
      pickRate: '47.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 62,
      winRate: '51.75%',
      pickRate: '50.64%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 96,
      winRate: '47.25%',
      pickRate: '51.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 68,
      winRate: '49.60%',
      pickRate: '46.14%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 235,
      winRate: '48.40%',
      pickRate: '47.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 127,
      winRate: '49.07%',
      pickRate: '47.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 254,
      winRate: '50.77%',
      pickRate: '53.78%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 60,
      winRate: '48.71%',
      pickRate: '51.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 101,
      winRate: '48.37%',
      pickRate: '53.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 38,
      winRate: '49.40%',
      pickRate: '53.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 41,
      winRate: '47.08%',
      pickRate: '47.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 240,
      winRate: '54.75%',
      pickRate: '45.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 34,
      winRate: '45.79%',
      pickRate: '45.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 245,
      winRate: '51.82%',
      pickRate: '53.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 105,
      winRate: '53.60%',
      pickRate: '46.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 113,
      winRate: '54.19%',
      pickRate: '54.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 115,
      winRate: '53.29%',
      pickRate: '47.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 35,
      winRate: '51.35%',
      pickRate: '54.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 85,
      winRate: '49.21%',
      pickRate: '45.90%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 134,
      winRate: '45.17%',
      pickRate: '51.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 81,
      winRate: '49.98%',
      pickRate: '45.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 222,
      winRate: '53.61%',
      pickRate: '51.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 29,
      winRate: '51.62%',
      pickRate: '51.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 136,
      winRate: '50.21%',
      pickRate: '50.08%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 63,
      winRate: '53.51%',
      pickRate: '54.71%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 360,
      winRate: '45.62%',
      pickRate: '50.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 58,
      winRate: '49.39%',
      pickRate: '53.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 31,
      winRate: '45.60%',
      pickRate: '53.50%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 142,
      winRate: '48.84%',
      pickRate: '54.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 17,
      winRate: '50.25%',
      pickRate: '52.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 37,
      winRate: '51.79%',
      pickRate: '54.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 1,
      winRate: '45.54%',
      pickRate: '49.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 114,
      winRate: '46.01%',
      pickRate: '52.41%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 30,
      winRate: '47.05%',
      pickRate: '51.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 33,
      winRate: '45.04%',
      pickRate: '46.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 19,
      winRate: '54.67%',
      pickRate: '52.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 143,
      winRate: '50.70%',
      pickRate: '52.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 238,
      winRate: '51.10%',
      pickRate: '50.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 8,
      winRate: '48.86%',
      pickRate: '49.17%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 27,
      winRate: '53.08%',
      pickRate: '51.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 122,
      winRate: '48.50%',
      pickRate: '47.40%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 82,
      winRate: '54.67%',
      pickRate: '52.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 83,
      winRate: '47.82%',
      pickRate: '53.66%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 48,
      winRate: '47.44%',
      pickRate: '50.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 12,
      winRate: '51.75%',
      pickRate: '52.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 150,
      winRate: '53.87%',
      pickRate: '54.15%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 236,
      winRate: '49.78%',
      pickRate: '45.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 246,
      winRate: '46.48%',
      pickRate: '50.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 92,
      winRate: '49.05%',
      pickRate: '51.57%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 7,
      winRate: '45.53%',
      pickRate: '47.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 11,
      winRate: '48.89%',
      pickRate: '53.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 25,
      winRate: '50.66%',
      pickRate: '49.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 429,
      winRate: '47.03%',
      pickRate: '52.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 36,
      winRate: '54.86%',
      pickRate: '48.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 32,
      winRate: '54.04%',
      pickRate: '45.58%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 22,
      winRate: '53.05%',
      pickRate: '45.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 5,
      winRate: '50.77%',
      pickRate: '46.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 412,
      winRate: '47.63%',
      pickRate: '54.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 3,
      winRate: '49.22%',
      pickRate: '54.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 777,
      winRate: '45.72%',
      pickRate: '51.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 203,
      winRate: '50.20%',
      pickRate: '54.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 117,
      winRate: '51.94%',
      pickRate: '49.39%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 57,
      winRate: '54.73%',
      pickRate: '46.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 45,
      winRate: '47.55%',
      pickRate: '52.00%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 523,
      winRate: '54.77%',
      pickRate: '52.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 6,
      winRate: '50.15%',
      pickRate: '48.66%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 268,
      winRate: '51.43%',
      pickRate: '51.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 98,
      winRate: '45.37%',
      pickRate: '54.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 4,
      winRate: '51.31%',
      pickRate: '47.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 40,
      winRate: '48.94%',
      pickRate: '53.14%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 69,
      winRate: '48.29%',
      pickRate: '51.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 223,
      winRate: '45.11%',
      pickRate: '51.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 84,
      winRate: '47.55%',
      pickRate: '46.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 56,
      winRate: '47.57%',
      pickRate: '50.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 164,
      winRate: '54.75%',
      pickRate: '50.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 39,
      winRate: '50.23%',
      pickRate: '51.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 157,
      winRate: '54.97%',
      pickRate: '52.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 555,
      winRate: '50.01%',
      pickRate: '54.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 497,
      winRate: '48.48%',
      pickRate: '52.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 106,
      winRate: '49.05%',
      pickRate: '48.64%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 50,
      winRate: '54.08%',
      pickRate: '48.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 104,
      winRate: '53.19%',
      pickRate: '50.27%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 20,
      winRate: '52.56%',
      pickRate: '47.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 78,
      winRate: '45.03%',
      pickRate: '46.63%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 518,
      winRate: '48.66%',
      pickRate: '48.36%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 163,
      winRate: '51.05%',
      pickRate: '53.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 72,
      winRate: '48.08%',
      pickRate: '54.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 526,
      winRate: '48.04%',
      pickRate: '45.32%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 91,
      winRate: '48.26%',
      pickRate: '46.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 161,
      winRate: '45.24%',
      pickRate: '49.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 516,
      winRate: '47.34%',
      pickRate: '46.22%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 121,
      winRate: '46.51%',
      pickRate: '52.67%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 266,
      winRate: '48.70%',
      pickRate: '50.39%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 16,
      winRate: '52.95%',
      pickRate: '50.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 350,
      winRate: '46.86%',
      pickRate: '45.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 141,
      winRate: '50.73%',
      pickRate: '45.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 44,
      winRate: '45.61%',
      pickRate: '49.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 77,
      winRate: '51.79%',
      pickRate: '48.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 76,
      winRate: '45.76%',
      pickRate: '47.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 110,
      winRate: '54.74%',
      pickRate: '49.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 120,
      winRate: '47.15%',
      pickRate: '53.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 64,
      winRate: '53.59%',
      pickRate: '48.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 51,
      winRate: '52.91%',
      pickRate: '46.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 517,
      winRate: '50.10%',
      pickRate: '54.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 103,
      winRate: '53.26%',
      pickRate: '48.52%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 55,
      winRate: '53.34%',
      pickRate: '54.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 427,
      winRate: '49.46%',
      pickRate: '45.66%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 26,
      winRate: '48.12%',
      pickRate: '47.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 111,
      winRate: '48.75%',
      pickRate: '48.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 53,
      winRate: '48.93%',
      pickRate: '47.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 13,
      winRate: '46.67%',
      pickRate: '45.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 498,
      winRate: '47.21%',
      pickRate: '49.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 107,
      winRate: '46.78%',
      pickRate: '45.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 86,
      winRate: '51.86%',
      pickRate: '45.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 876,
      winRate: '45.60%',
      pickRate: '51.09%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 133,
      winRate: '52.11%',
      pickRate: '49.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 59,
      winRate: '54.87%',
      pickRate: '49.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 42,
      winRate: '53.61%',
      pickRate: '48.17%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 421,
      winRate: '49.48%',
      pickRate: '51.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 126,
      winRate: '50.62%',
      pickRate: '49.86%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 74,
      winRate: '46.21%',
      pickRate: '51.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 202,
      winRate: '46.65%',
      pickRate: '46.10%',
      tableDataType: 'WinPickTableData',
    },
  ] as WinPickRateTableData[],
  픽률: [
    {
      championId: 81,
      winRate: '53.16%',
      pickRate: '52.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 19,
      winRate: '54.36%',
      pickRate: '49.54%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 1,
      winRate: '46.28%',
      pickRate: '54.37%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 74,
      winRate: '53.36%',
      pickRate: '52.10%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 360,
      winRate: '52.42%',
      pickRate: '53.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 84,
      winRate: '53.10%',
      pickRate: '46.26%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 75,
      winRate: '49.88%',
      pickRate: '50.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 57,
      winRate: '45.27%',
      pickRate: '54.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 79,
      winRate: '51.86%',
      pickRate: '46.15%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 498,
      winRate: '52.97%',
      pickRate: '45.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 268,
      winRate: '47.69%',
      pickRate: '54.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 12,
      winRate: '47.22%',
      pickRate: '45.77%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 3,
      winRate: '50.97%',
      pickRate: '51.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 91,
      winRate: '49.80%',
      pickRate: '50.72%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 114,
      winRate: '50.65%',
      pickRate: '46.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 150,
      winRate: '46.44%',
      pickRate: '46.64%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 53,
      winRate: '45.48%',
      pickRate: '53.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 14,
      winRate: '51.64%',
      pickRate: '51.75%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 245,
      winRate: '52.75%',
      pickRate: '52.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 96,
      winRate: '51.39%',
      pickRate: '53.30%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 266,
      winRate: '47.74%',
      pickRate: '50.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 145,
      winRate: '48.02%',
      pickRate: '48.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 82,
      winRate: '48.74%',
      pickRate: '48.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 17,
      winRate: '46.83%',
      pickRate: '53.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 112,
      winRate: '54.52%',
      pickRate: '52.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 20,
      winRate: '50.66%',
      pickRate: '45.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 45,
      winRate: '51.99%',
      pickRate: '52.63%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 41,
      winRate: '49.72%',
      pickRate: '45.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 164,
      winRate: '51.96%',
      pickRate: '54.01%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 42,
      winRate: '46.13%',
      pickRate: '46.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 432,
      winRate: '53.37%',
      pickRate: '49.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 876,
      winRate: '50.29%',
      pickRate: '51.42%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 48,
      winRate: '46.62%',
      pickRate: '50.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 523,
      winRate: '54.01%',
      pickRate: '48.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 37,
      winRate: '49.69%',
      pickRate: '54.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 119,
      winRate: '45.80%',
      pickRate: '52.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 31,
      winRate: '53.35%',
      pickRate: '53.63%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 875,
      winRate: '54.57%',
      pickRate: '54.51%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 110,
      winRate: '53.78%',
      pickRate: '53.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 10,
      winRate: '46.39%',
      pickRate: '52.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 163,
      winRate: '47.74%',
      pickRate: '54.73%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 147,
      winRate: '49.72%',
      pickRate: '46.98%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 143,
      winRate: '45.38%',
      pickRate: '54.58%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 39,
      winRate: '50.27%',
      pickRate: '51.09%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 103,
      winRate: '49.92%',
      pickRate: '54.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 56,
      winRate: '48.16%',
      pickRate: '46.37%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 222,
      winRate: '45.36%',
      pickRate: '51.98%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 111,
      winRate: '45.43%',
      pickRate: '46.68%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 68,
      winRate: '50.36%',
      pickRate: '52.13%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 555,
      winRate: '46.28%',
      pickRate: '49.62%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 99,
      winRate: '45.28%',
      pickRate: '52.04%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 102,
      winRate: '45.06%',
      pickRate: '46.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 23,
      winRate: '53.09%',
      pickRate: '50.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 236,
      winRate: '45.62%',
      pickRate: '51.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 89,
      winRate: '45.97%',
      pickRate: '47.78%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 127,
      winRate: '54.37%',
      pickRate: '48.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 122,
      winRate: '46.24%',
      pickRate: '45.37%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 64,
      winRate: '50.38%',
      pickRate: '55.00%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 161,
      winRate: '50.25%',
      pickRate: '45.47%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 35,
      winRate: '47.83%',
      pickRate: '48.90%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 113,
      winRate: '47.24%',
      pickRate: '50.88%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 29,
      winRate: '48.05%',
      pickRate: '48.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 141,
      winRate: '51.97%',
      pickRate: '50.57%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 60,
      winRate: '48.39%',
      pickRate: '51.49%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 133,
      winRate: '50.84%',
      pickRate: '47.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 44,
      winRate: '50.32%',
      pickRate: '53.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 157,
      winRate: '46.85%',
      pickRate: '49.31%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 85,
      winRate: '45.26%',
      pickRate: '46.60%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 134,
      winRate: '52.81%',
      pickRate: '46.91%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 34,
      winRate: '54.63%',
      pickRate: '52.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 15,
      winRate: '48.51%',
      pickRate: '51.08%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 11,
      winRate: '51.14%',
      pickRate: '53.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 267,
      winRate: '52.92%',
      pickRate: '45.52%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 154,
      winRate: '53.76%',
      pickRate: '45.70%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 98,
      winRate: '52.25%',
      pickRate: '45.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 27,
      winRate: '53.63%',
      pickRate: '48.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 58,
      winRate: '49.48%',
      pickRate: '48.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 86,
      winRate: '51.99%',
      pickRate: '51.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 429,
      winRate: '48.48%',
      pickRate: '48.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 33,
      winRate: '45.69%',
      pickRate: '54.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 40,
      winRate: '52.12%',
      pickRate: '47.28%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 21,
      winRate: '45.02%',
      pickRate: '46.53%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 518,
      winRate: '46.17%',
      pickRate: '52.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 350,
      winRate: '53.45%',
      pickRate: '46.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 107,
      winRate: '51.33%',
      pickRate: '54.24%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 142,
      winRate: '49.71%',
      pickRate: '52.39%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 78,
      winRate: '53.85%',
      pickRate: '50.58%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 24,
      winRate: '53.49%',
      pickRate: '47.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 51,
      winRate: '45.67%',
      pickRate: '45.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 67,
      winRate: '52.71%',
      pickRate: '54.03%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 92,
      winRate: '47.10%',
      pickRate: '48.24%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 7,
      winRate: '47.52%',
      pickRate: '54.56%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 777,
      winRate: '53.46%',
      pickRate: '51.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 126,
      winRate: '52.31%',
      pickRate: '52.18%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 526,
      winRate: '47.64%',
      pickRate: '50.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 38,
      winRate: '45.14%',
      pickRate: '46.79%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 2,
      winRate: '45.57%',
      pickRate: '54.22%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 26,
      winRate: '45.81%',
      pickRate: '49.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 59,
      winRate: '53.08%',
      pickRate: '45.93%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 32,
      winRate: '48.44%',
      pickRate: '50.27%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 427,
      winRate: '51.62%',
      pickRate: '50.96%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 115,
      winRate: '48.69%',
      pickRate: '52.65%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 55,
      winRate: '45.36%',
      pickRate: '51.61%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 43,
      winRate: '53.31%',
      pickRate: '50.59%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 4,
      winRate: '47.79%',
      pickRate: '50.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 25,
      winRate: '52.94%',
      pickRate: '45.29%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 120,
      winRate: '46.92%',
      pickRate: '52.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 101,
      winRate: '48.43%',
      pickRate: '48.80%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 30,
      winRate: '52.44%',
      pickRate: '49.94%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 77,
      winRate: '48.64%',
      pickRate: '49.83%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 61,
      winRate: '54.00%',
      pickRate: '54.95%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 13,
      winRate: '46.10%',
      pickRate: '54.63%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 201,
      winRate: '45.03%',
      pickRate: '51.84%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 50,
      winRate: '46.01%',
      pickRate: '47.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 497,
      winRate: '48.48%',
      pickRate: '54.20%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 202,
      winRate: '53.64%',
      pickRate: '48.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 62,
      winRate: '47.82%',
      pickRate: '48.00%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 136,
      winRate: '52.85%',
      pickRate: '53.92%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 76,
      winRate: '47.54%',
      pickRate: '46.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 5,
      winRate: '47.14%',
      pickRate: '47.69%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 69,
      winRate: '53.37%',
      pickRate: '49.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 412,
      winRate: '47.05%',
      pickRate: '52.15%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 6,
      winRate: '53.12%',
      pickRate: '50.99%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 203,
      winRate: '46.40%',
      pickRate: '47.23%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 517,
      winRate: '46.82%',
      pickRate: '46.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 28,
      winRate: '49.96%',
      pickRate: '50.25%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 117,
      winRate: '49.93%',
      pickRate: '52.82%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 240,
      winRate: '50.40%',
      pickRate: '53.54%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 234,
      winRate: '46.89%',
      pickRate: '54.17%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 106,
      winRate: '47.14%',
      pickRate: '51.14%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 246,
      winRate: '51.87%',
      pickRate: '51.27%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 9,
      winRate: '47.05%',
      pickRate: '51.06%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 121,
      winRate: '48.47%',
      pickRate: '53.02%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 36,
      winRate: '52.15%',
      pickRate: '54.74%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 16,
      winRate: '54.20%',
      pickRate: '50.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 131,
      winRate: '54.42%',
      pickRate: '49.85%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 235,
      winRate: '48.89%',
      pickRate: '45.38%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 421,
      winRate: '45.58%',
      pickRate: '51.97%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 516,
      winRate: '51.02%',
      pickRate: '45.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 254,
      winRate: '47.85%',
      pickRate: '52.07%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 54,
      winRate: '52.38%',
      pickRate: '51.16%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 83,
      winRate: '45.84%',
      pickRate: '46.48%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 80,
      winRate: '49.85%',
      pickRate: '52.81%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 18,
      winRate: '46.40%',
      pickRate: '46.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 90,
      winRate: '48.07%',
      pickRate: '50.19%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 8,
      winRate: '49.38%',
      pickRate: '45.57%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 420,
      winRate: '51.85%',
      pickRate: '52.87%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 223,
      winRate: '51.45%',
      pickRate: '45.35%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 63,
      winRate: '54.08%',
      pickRate: '45.55%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 238,
      winRate: '45.21%',
      pickRate: '52.70%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 72,
      winRate: '46.28%',
      pickRate: '50.50%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 105,
      winRate: '48.74%',
      pickRate: '53.89%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 104,
      winRate: '51.12%',
      pickRate: '49.45%',
      tableDataType: 'WinPickTableData',
    },
    {
      championId: 22,
      winRate: '54.93%',
      pickRate: '54.53%',
      tableDataType: 'WinPickTableData',
    },
  ] as WinPickRateTableData[],
  벤률: [
    {
      championId: 120,
      banRate: '52.54%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 84,
      banRate: '46.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 56,
      banRate: '50.64%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 1,
      banRate: '54.37%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 72,
      banRate: '50.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 21,
      banRate: '46.05%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 133,
      banRate: '51.69%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 202,
      banRate: '51.52%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 238,
      banRate: '52.39%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 36,
      banRate: '47.32%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 83,
      banRate: '47.65%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 44,
      banRate: '53.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 145,
      banRate: '51.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 76,
      banRate: '47.80%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 9,
      banRate: '45.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 222,
      banRate: '50.03%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 516,
      banRate: '52.88%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 16,
      banRate: '45.79%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 13,
      banRate: '52.80%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 34,
      banRate: '50.64%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 24,
      banRate: '46.47%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 432,
      banRate: '45.20%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 57,
      banRate: '53.20%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 58,
      banRate: '52.34%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 59,
      banRate: '50.58%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 75,
      banRate: '46.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 98,
      banRate: '46.63%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 245,
      banRate: '49.34%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 350,
      banRate: '54.18%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 164,
      banRate: '54.59%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 15,
      banRate: '53.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 526,
      banRate: '46.68%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 254,
      banRate: '51.91%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 119,
      banRate: '47.63%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 68,
      banRate: '49.38%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 64,
      banRate: '53.13%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 86,
      banRate: '49.83%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 523,
      banRate: '52.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 266,
      banRate: '52.79%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 11,
      banRate: '54.17%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 107,
      banRate: '53.61%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 111,
      banRate: '54.48%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 45,
      banRate: '53.85%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 5,
      banRate: '50.61%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 555,
      banRate: '54.35%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 427,
      banRate: '52.10%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 54,
      banRate: '54.88%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 77,
      banRate: '49.73%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 14,
      banRate: '46.81%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 79,
      banRate: '47.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 126,
      banRate: '51.88%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 42,
      banRate: '52.14%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 23,
      banRate: '45.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 61,
      banRate: '47.19%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 112,
      banRate: '53.36%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 267,
      banRate: '47.41%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 48,
      banRate: '54.99%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 101,
      banRate: '52.37%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 113,
      banRate: '50.03%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 35,
      banRate: '48.50%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 10,
      banRate: '50.66%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 43,
      banRate: '49.83%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 429,
      banRate: '46.78%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 74,
      banRate: '54.01%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 22,
      banRate: '48.71%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 236,
      banRate: '47.51%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 141,
      banRate: '50.53%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 136,
      banRate: '50.49%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 89,
      banRate: '48.93%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 99,
      banRate: '46.68%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 115,
      banRate: '48.10%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 163,
      banRate: '48.53%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 39,
      banRate: '50.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 421,
      banRate: '51.68%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 518,
      banRate: '53.50%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 134,
      banRate: '50.37%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 38,
      banRate: '49.67%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 497,
      banRate: '54.57%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 412,
      banRate: '48.52%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 4,
      banRate: '51.73%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 223,
      banRate: '45.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 234,
      banRate: '47.42%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 246,
      banRate: '50.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 154,
      banRate: '52.70%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 27,
      banRate: '53.95%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 29,
      banRate: '53.01%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 41,
      banRate: '51.30%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 92,
      banRate: '48.44%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 33,
      banRate: '48.68%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 121,
      banRate: '53.60%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 420,
      banRate: '52.14%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 6,
      banRate: '51.61%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 203,
      banRate: '51.15%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 12,
      banRate: '45.29%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 360,
      banRate: '46.86%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 875,
      banRate: '51.69%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 127,
      banRate: '53.61%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 17,
      banRate: '49.89%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 157,
      banRate: '54.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 62,
      banRate: '48.16%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 240,
      banRate: '49.38%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 37,
      banRate: '49.98%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 51,
      banRate: '45.09%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 50,
      banRate: '50.03%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 8,
      banRate: '45.60%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 19,
      banRate: '51.30%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 85,
      banRate: '54.62%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 498,
      banRate: '51.74%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 81,
      banRate: '45.59%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 20,
      banRate: '47.77%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 104,
      banRate: '47.91%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 147,
      banRate: '51.62%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 268,
      banRate: '54.73%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 114,
      banRate: '53.56%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 3,
      banRate: '45.99%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 69,
      banRate: '54.64%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 150,
      banRate: '50.27%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 102,
      banRate: '52.19%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 55,
      banRate: '46.75%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 7,
      banRate: '49.04%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 106,
      banRate: '51.43%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 517,
      banRate: '47.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 40,
      banRate: '54.81%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 103,
      banRate: '45.70%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 28,
      banRate: '49.81%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 876,
      banRate: '50.31%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 25,
      banRate: '49.44%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 80,
      banRate: '46.87%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 131,
      banRate: '46.79%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 117,
      banRate: '50.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 161,
      banRate: '51.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 105,
      banRate: '48.53%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 777,
      banRate: '46.89%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 235,
      banRate: '54.02%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 96,
      banRate: '52.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 91,
      banRate: '50.56%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 143,
      banRate: '49.19%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 122,
      banRate: '45.71%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 31,
      banRate: '50.90%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 142,
      banRate: '53.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 63,
      banRate: '49.92%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 110,
      banRate: '49.34%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 67,
      banRate: '50.17%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 90,
      banRate: '46.70%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 30,
      banRate: '53.97%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 32,
      banRate: '49.07%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 60,
      banRate: '53.21%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 18,
      banRate: '52.66%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 82,
      banRate: '50.33%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 53,
      banRate: '51.13%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 2,
      banRate: '45.45%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 78,
      banRate: '51.03%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 201,
      banRate: '46.57%',
      tableDataType: 'BanTableData',
    },
    {
      championId: 26,
      banRate: '45.35%',
      tableDataType: 'BanTableData',
    },
  ] as BanRateTableData[],
};
