export type ChampionPosition = 'TOP' | 'MID' | 'ADC' | 'SUPPORT' | 'JUNGLE';
export type ChampionPositionMapType = Record<ChampionPosition, string>;
export type ChampionsMetaType = Record<string, ChampionMeta>;
export const ChampionPositionMap: ChampionPositionMapType = {
  TOP: '탑',
  MID: '미드',
  ADC: '바텀',
  JUNGLE: '정글',
  SUPPORT: '서포터',
};
export interface ChampionMeta {
  idx: number; // Image Sprites을 위한 인덱스
  championId: number; // championId
  name: string; // 챔피언 한글 이름
  chosung: string; // 챔피언 한글 이름 초성
  positions: ChampionPosition[]; // 챔피언 라인 포지션
}
export const championsMeta: ChampionsMetaType = {
  aatrox: { name: '아트록스', chosung: 'ㅇㅌㄹㅅ', positions: ['TOP'], idx: 0, championId: 266 },
  ahri: { name: '아리', chosung: 'ㅇㄹ', positions: ['MID'], idx: 1, championId: 103 },
  akali: { name: '아칼리', chosung: 'ㅇㅋㄹ', positions: ['TOP', 'MID'], idx: 2, championId: 84 },
  alistar: {
    name: '알리스타',
    chosung: 'ㅇㄹㅅㅌ',
    positions: ['SUPPORT'],
    idx: 3,
    championId: 12,
  },
  amumu: { name: '아무무', chosung: 'ㅇㅁㅁ', positions: ['JUNGLE'], idx: 4, championId: 32 },
  anivia: {
    name: '애니비아',
    chosung: 'ㅇㄴㅂㅇ',
    positions: ['MID', 'SUPPORT'],
    idx: 5,
    championId: 34,
  },
  annie: { name: '애니', chosung: 'ㅇㄴ', positions: ['MID'], idx: 6, championId: 1 },
  aphelios: {
    name: '아펠리오스',
    chosung: 'ㅇㅍㄹㅇㅅ',
    positions: ['ADC'],
    idx: 7,
    championId: 523,
  },
  ashe: { name: '애쉬', chosung: 'ㅇㅅ', positions: ['ADC', 'SUPPORT'], idx: 8, championId: 22 },
  aurelionsol: {
    name: '아우렐리온솔',
    chosung: 'ㅇㅇㄹㄹㅇㅅ',
    positions: ['MID'],
    idx: 9,
    championId: 136,
  },
  azir: { name: '아지르', chosung: 'ㅇㅈㄹ', positions: ['MID'], idx: 10, championId: 268 },
  bard: { name: '바드', chosung: 'ㅂㄷ', positions: ['SUPPORT'], idx: 11, championId: 432 },
  blitzcrank: {
    name: '블리츠크랭크',
    chosung: 'ㅂㄹㅊㅋㄹㅋ',
    positions: ['SUPPORT'],
    idx: 12,
    championId: 53,
  },
  brand: { name: '브랜드', chosung: 'ㅂㄹㄷ', positions: ['SUPPORT'], idx: 13, championId: 63 },
  braum: { name: '브라움', chosung: 'ㅂㄹㅇ', positions: ['SUPPORT'], idx: 14, championId: 201 },
  caitlyn: { name: '케이틀린', chosung: 'ㅋㅇㅌㄹ', positions: ['ADC'], idx: 15, championId: 51 },
  camille: { name: '카밀', chosung: 'ㅋㅁ', positions: ['TOP', 'MID'], idx: 16, championId: 164 },
  cassiopeia: {
    name: '카시오페아',
    chosung: 'ㅋㅅㅇㅍㅇ',
    positions: ['MID'],
    idx: 17,
    championId: 69,
  },
  chogath: {
    name: '초가스',
    chosung: 'ㅊㄱㅅ',
    positions: ['TOP', 'MID'],
    idx: 18,
    championId: 31,
  },
  corki: { name: '코르키', chosung: 'ㅋㄹㅋ', positions: ['MID'], idx: 19, championId: 42 },
  darius: { name: '다리우스', chosung: 'ㄷㄹㅇㅅ', positions: ['TOP'], idx: 20, championId: 122 },
  diana: { name: '다이애나', chosung: 'ㄷㅇㅇㄴ', positions: ['MID'], idx: 21, championId: 131 },
  draven: { name: '드레이븐', chosung: 'ㄷㄹㅇㅂ', positions: ['ADC'], idx: 22, championId: 119 },
  drmundo: {
    name: '문도박사',
    chosung: 'ㅁㄷㅂㅅ',
    positions: ['JUNGLE'],
    idx: 23,
    championId: 36,
  },
  ekko: { name: '에코', chosung: 'ㅇㅋ', positions: ['JUNGLE', 'MID'], idx: 24, championId: 245 },
  elise: { name: '엘리스', chosung: 'ㅇㄹㅅ', positions: ['JUNGLE'], idx: 25, championId: 60 },
  evelynn: { name: '이블린', chosung: 'ㅇㅂㄹ', positions: ['JUNGLE'], idx: 26, championId: 28 },
  ezreal: { name: '이즈리얼', chosung: 'ㅇㅈㄹㅇ', positions: ['ADC'], idx: 27, championId: 81 },
  fiddlesticks: {
    name: '피들스틱',
    chosung: 'ㅍㄷㅅㅌ',
    positions: ['JUNGLE'],
    idx: 28,
    championId: 9,
  },
  fiora: { name: '피오라', chosung: 'ㅍㅇㄹ', positions: ['TOP'], idx: 29, championId: 114 },
  fizz: { name: '피즈', chosung: 'ㅍㅈ', positions: ['MID'], idx: 30, championId: 105 },
  galio: {
    name: '갈리오',
    chosung: 'ㄱㄹㅇ',
    positions: ['MID', 'SUPPORT'],
    idx: 31,
    championId: 3,
  },
  gangplank: { name: '갱플랭크', chosung: 'ㄱㅍㄹㅋ', positions: ['TOP'], idx: 32, championId: 41 },
  garen: { name: '가렌', chosung: 'ㄱㄹ', positions: ['TOP', 'MID'], idx: 33, championId: 86 },
  gnar: { name: '나르', chosung: 'ㄴㄹ', positions: ['TOP'], idx: 34, championId: 150 },
  gragas: {
    name: '그라가스',
    chosung: 'ㄱㄹㄱㅅ',
    positions: ['SUPPORT', 'TOP', 'JUNGLE'],
    idx: 35,
    championId: 79,
  },
  graves: {
    name: '그레이브즈',
    chosung: 'ㄱㄹㅇㅂㅈ',
    positions: ['JUNGLE'],
    idx: 36,
    championId: 104,
  },
  hecarim: { name: '헤카림', chosung: 'ㅎㅋㄹ', positions: ['JUNGLE'], idx: 37, championId: 120 },
  heimerdinger: {
    name: '하이머딩거',
    chosung: 'ㅎㅇㅁㄷㄱ',
    positions: ['TOP'],
    idx: 38,
    championId: 74,
  },
  illaoi: { name: '일라오이', chosung: 'ㅇㄹㅇㅇ', positions: ['TOP'], idx: 39, championId: 420 },
  irelia: {
    name: '이렐리아',
    chosung: 'ㅇㄹㄹㅇ',
    positions: ['TOP', 'MID'],
    idx: 40,
    championId: 39,
  },
  ivern: { name: '아이번', chosung: 'ㅇㅇㅂ', positions: ['JUNGLE'], idx: 41, championId: 427 },
  janna: { name: '잔나', chosung: 'ㅈㄴ', positions: ['SUPPORT'], idx: 42, championId: 40 },
  jarvaniv: {
    name: '자르반4세',
    chosung: 'ㅈㄹㅂ4ㅅ',
    positions: ['JUNGLE'],
    idx: 43,
    championId: 59,
  },
  jax: { name: '잭스', chosung: 'ㅈㅅ', positions: ['TOP', 'JUNGLE'], idx: 44, championId: 24 },
  jayce: { name: '제이스', chosung: 'ㅈㅇㅅ', positions: ['TOP', 'MID'], idx: 45, championId: 126 },
  jhin: { name: '진', chosung: 'ㅈ', positions: ['ADC'], idx: 46, championId: 202 },
  jinx: { name: '징크스', chosung: 'ㅈㅋㅅ', positions: ['ADC'], idx: 47, championId: 222 },
  kaisa: { name: '카이사', chosung: 'ㅋㅇㅅ', positions: ['ADC'], idx: 48, championId: 145 },
  kalista: {
    name: '칼리스타',
    chosung: 'ㅋㄹㅅㅌ',
    positions: ['ADC', 'TOP'],
    idx: 49,
    championId: 429,
  },
  karma: { name: '카르마', chosung: 'ㅋㄹㅁ', positions: ['SUPPORT'], idx: 50, championId: 43 },
  karthus: { name: '카서스', chosung: 'ㅋㅅㅅ', positions: ['JUNGLE'], idx: 51, championId: 30 },
  kassadin: { name: '카사딘', chosung: 'ㅋㅅㄷ', positions: ['MID'], idx: 52, championId: 38 },
  katarina: { name: '카타리나', chosung: 'ㅋㅌㄹㄴ', positions: ['MID'], idx: 53, championId: 55 },
  kayle: { name: '케일', chosung: 'ㅋㅇ', positions: ['TOP'], idx: 54, championId: 10 },
  kayn: { name: '케인', chosung: 'ㅋㅇ', positions: ['JUNGLE'], idx: 55, championId: 141 },
  kennen: { name: '케넨', chosung: 'ㅋㄴ', positions: ['TOP'], idx: 56, championId: 85 },
  khazix: { name: '카직스', chosung: 'ㅋㅈㅅ', positions: ['JUNGLE'], idx: 57, championId: 121 },
  kindred: {
    name: '킨드레드',
    chosung: 'ㅋㄷㄹㄷ',
    positions: ['JUNGLE'],
    idx: 58,
    championId: 203,
  },
  kled: { name: '클레드', chosung: 'ㅋㄹㄷ', positions: ['TOP', 'MID'], idx: 59, championId: 240 },
  kogmaw: { name: '코그모', chosung: 'ㅋㄱㅁ', positions: ['ADC'], idx: 60, championId: 96 },
  leblanc: { name: '르블랑', chosung: 'ㄹㅂㄹ', positions: ['MID'], idx: 61, championId: 7 },
  leesin: { name: '리신', chosung: 'ㄹㅅ', positions: ['JUNGLE'], idx: 62, championId: 64 },
  leona: { name: '레오나', chosung: 'ㄹㅇㄴ', positions: ['SUPPORT'], idx: 63, championId: 89 },
  lillia: { name: '릴리아', chosung: 'ㄹㄹㅇ', positions: ['JUNGLE'], idx: 64, championId: 876 },
  lissandra: {
    name: '리산드라',
    chosung: 'ㄹㅅㄷㄹ',
    positions: ['MID'],
    idx: 65,
    championId: 127,
  },
  lucian: {
    name: '루시안',
    chosung: 'ㄹㅅㅇ',
    positions: ['MID', 'ADC', 'TOP'],
    idx: 66,
    championId: 236,
  },
  lulu: { name: '룰루', chosung: 'ㄹㄹ', positions: ['SUPPORT'], idx: 67, championId: 117 },
  lux: { name: '럭스', chosung: 'ㄹㅅ', positions: ['SUPPORT', 'MID'], idx: 68, championId: 99 },
  malphite: {
    name: '말파이트',
    chosung: 'ㅁㅍㅇㅌ',
    positions: ['TOP', 'MID'],
    idx: 69,
    championId: 54,
  },
  malzahar: { name: '말자하', chosung: 'ㅁㅈㅎ', positions: ['MID'], idx: 70, championId: 90 },
  maokai: {
    name: '마오카이',
    chosung: 'ㅁㅇㅋㅇ',
    positions: ['SUPPORT', 'TOP'],
    idx: 71,
    championId: 57,
  },
  masteryi: {
    name: '마스터이',
    chosung: 'ㅁㅅㅌㅇ',
    positions: ['JUNGLE'],
    idx: 72,
    championId: 11,
  },
  missfortune: {
    name: '미스포츈',
    chosung: 'ㅁㅅㅍㅊ',
    positions: ['ADC'],
    idx: 73,
    championId: 21,
  },
  monkeyking: { name: '오공', chosung: 'ㅇㄱ', positions: ['TOP'], idx: 74, championId: 62 },
  mordekaiser: {
    name: '모데카이저',
    chosung: 'ㅁㄷㅋㅇㅈ',
    positions: ['TOP'],
    idx: 75,
    championId: 82,
  },
  morgana: {
    name: '모르가나',
    chosung: 'ㅁㄹㄱㄴ',
    positions: ['SUPPORT'],
    idx: 76,
    championId: 25,
  },
  nami: { name: '나미', chosung: 'ㄴㅁ', positions: ['SUPPORT'], idx: 77, championId: 267 },
  nasus: { name: '나서스', chosung: 'ㄴㅅㅅ', positions: ['TOP'], idx: 78, championId: 75 },
  nautilus: {
    name: '노틸러스',
    chosung: 'ㄴㅌㄹㅅ',
    positions: ['SUPPORT'],
    idx: 79,
    championId: 111,
  },
  neeko: { name: '니코', chosung: 'ㄴㅋ', positions: ['MID', 'SUPPORT'], idx: 80, championId: 518 },
  nidalee: { name: '니달리', chosung: 'ㄴㄷㄹ', positions: ['JUNGLE'], idx: 81, championId: 76 },
  nocturne: {
    name: '녹턴',
    chosung: 'ㄴㅌ',
    positions: ['JUNGLE', 'MID', 'TOP'],
    idx: 82,
    championId: 56,
  },
  nunu: {
    name: '누누와윌럼프',
    chosung: 'ㄴㄴㅇㅇㄹㅍ',
    positions: ['JUNGLE', 'MID'],
    idx: 83,
    championId: 20,
  },
  olaf: { name: '올라프', chosung: 'ㅇㄹㅍ', positions: ['JUNGLE'], idx: 84, championId: 2 },
  orianna: { name: '오리아나', chosung: 'ㅇㄹㅇㄴ', positions: ['MID'], idx: 85, championId: 61 },
  ornn: { name: '오른', chosung: 'ㅇㄹ', positions: ['TOP'], idx: 86, championId: 516 },
  pantheon: {
    name: '판테온',
    chosung: 'ㅍㅌㅇ',
    positions: ['MID', 'SUPPORT', 'TOP'],
    idx: 87,
    championId: 80,
  },
  poppy: {
    name: '뽀삐',
    chosung: 'ㅃㅃ',
    positions: ['JUNGLE', 'TOP', 'SUPPORT'],
    idx: 88,
    championId: 78,
  },
  pyke: { name: '파이크', chosung: 'ㅍㅇㅋ', positions: ['SUPPORT'], idx: 89, championId: 555 },
  qiyana: { name: '키아나', chosung: 'ㅋㅇㄴ', positions: ['MID'], idx: 90, championId: 246 },
  quinn: { name: '퀸', chosung: 'ㅋ', positions: ['TOP'], idx: 91, championId: 133 },
  rakan: { name: '라칸', chosung: 'ㄹㅋ', positions: ['SUPPORT'], idx: 92, championId: 497 },
  rammus: { name: '람머스', chosung: 'ㄹㅁㅅ', positions: ['JUNGLE'], idx: 93, championId: 33 },
  reksai: { name: '렉사이', chosung: 'ㄹㅅㅇ', positions: ['JUNGLE'], idx: 94, championId: 421 },
  rell: { name: '렐', chosung: 'ㄹ', positions: ['SUPPORT'], idx: 95, championId: 526 },
  renekton: {
    name: '레넥톤',
    chosung: 'ㄹㄴㅌ',
    positions: ['TOP', 'MID'],
    idx: 96,
    championId: 58,
  },
  rengar: { name: '렝가', chosung: 'ㄹㄱ', positions: ['TOP', 'JUNGLE'], idx: 97, championId: 107 },
  riven: { name: '리븐', chosung: 'ㄹㅂ', positions: ['TOP', 'MID'], idx: 98, championId: 92 },
  rumble: { name: '럼블', chosung: 'ㄹㅂ', positions: ['MID', 'TOP'], idx: 99, championId: 68 },
  ryze: { name: '라이즈', chosung: 'ㄹㅇㅈ', positions: ['TOP', 'MID'], idx: 100, championId: 13 },
  samira: { name: '사미라', chosung: 'ㅅㅁㄹ', positions: ['ADC'], idx: 101, championId: 360 },
  sejuani: {
    name: '세주아니',
    chosung: 'ㅅㅈㅇㄴ',
    positions: ['JUNGLE', 'TOP'],
    idx: 102,
    championId: 113,
  },
  senna: {
    name: '세나',
    chosung: 'ㅅㄴ',
    positions: ['SUPPORT', 'ADC'],
    idx: 103,
    championId: 235,
  },
  seraphine: {
    name: '세라핀',
    chosung: 'ㅅㄹㅍ',
    positions: ['SUPPORT', 'MID'],
    idx: 104,
    championId: 147,
  },
  sett: {
    name: '세트',
    chosung: 'ㅅㅌ',
    positions: ['TOP', 'SUPPORT', 'MID'],
    idx: 105,
    championId: 875,
  },
  shaco: {
    name: '샤코',
    chosung: 'ㅅㅋ',
    positions: ['JUNGLE', 'SUPPORT'],
    idx: 106,
    championId: 35,
  },
  shen: { name: '쉔', chosung: 'ㅅ', positions: ['TOP', 'SUPPORT'], idx: 107, championId: 98 },
  shyvana: { name: '쉬바나', chosung: 'ㅅㅂㄴ', positions: ['JUNGLE'], idx: 108, championId: 102 },
  singed: { name: '신지드', chosung: 'ㅅㅈㄷ', positions: ['TOP'], idx: 109, championId: 27 },
  sion: { name: '사이온', chosung: 'ㅅㅇㅇ', positions: ['TOP', 'MID'], idx: 110, championId: 14 },
  sivir: { name: '시비르', chosung: 'ㅅㅂㄹ', positions: ['ADC'], idx: 111, championId: 15 },
  skarner: { name: '스카너', chosung: 'ㅅㅋㄴ', positions: ['JUNGLE'], idx: 112, championId: 72 },
  sona: { name: '소나', chosung: 'ㅅㄴ', positions: ['SUPPORT'], idx: 113, championId: 37 },
  soraka: { name: '소라카', chosung: 'ㅅㄹㅋ', positions: ['SUPPORT'], idx: 114, championId: 16 },
  swain: {
    name: '스웨인',
    chosung: 'ㅅㅇㅇ',
    positions: ['SUPPORT', 'ADC'],
    idx: 115,
    championId: 50,
  },
  sylas: {
    name: '사일러스',
    chosung: 'ㅅㅇㄹㅅ',
    positions: ['MID', 'TOP'],
    idx: 116,
    championId: 517,
  },
  syndra: { name: '신드라', chosung: 'ㅅㄷㄹ', positions: ['MID'], idx: 117, championId: 134 },
  tahmkench: { name: '탐켄치', chosung: 'ㅌㅋㅊ', positions: ['ADC'], idx: 118, championId: 223 },
  taliyah: { name: '탈리야', chosung: 'ㅌㄹㅇ', positions: ['JUNGLE'], idx: 119, championId: 163 },
  talon: { name: '탈론', chosung: 'ㅌㄹ', positions: ['MID'], idx: 120, championId: 91 },
  taric: { name: '타릭', chosung: 'ㅌㄹ', positions: ['SUPPORT'], idx: 121, championId: 44 },
  teemo: { name: '티모', chosung: 'ㅌㅁ', positions: ['TOP'], idx: 122, championId: 17 },
  thresh: { name: '쓰레쉬', chosung: 'ㅆㄹㅅ', positions: ['SUPPORT'], idx: 123, championId: 412 },
  tristana: {
    name: '트리스타나',
    chosung: 'ㅌㄹㅅㅌㄴ',
    positions: ['ADC', 'MID'],
    idx: 124,
    championId: 18,
  },
  trundle: { name: '트런들', chosung: 'ㅌㄹㄷ', positions: ['JUNGLE'], idx: 125, championId: 48 },
  tryndamere: {
    name: '트린다미어',
    chosung: 'ㅌㄹㄷㅁㅇ',
    positions: ['TOP'],
    idx: 126,
    championId: 23,
  },
  twistedfate: {
    name: '트위스티드페이트',
    chosung: 'ㅌㅇㅅㅌㄷㅍㅇㅌ',
    positions: ['MID'],
    idx: 127,
    championId: 4,
  },
  twitch: { name: '트위치', chosung: 'ㅌㅇㅊ', positions: ['ADC'], idx: 128, championId: 29 },
  udyr: { name: '우디르', chosung: 'ㅇㄷㄹ', positions: ['JUNGLE'], idx: 129, championId: 77 },
  urgot: { name: '우르곳', chosung: 'ㅇㄹㄱ', positions: ['TOP'], idx: 130, championId: 6 },
  varus: { name: '바루스', chosung: 'ㅂㄹㅅ', positions: ['ADC'], idx: 131, championId: 110 },
  vayne: { name: '베인', chosung: 'ㅂㅇ', positions: ['ADC', 'TOP'], idx: 132, championId: 67 },
  veigar: {
    name: '베이가',
    chosung: 'ㅂㅇㄱ',
    positions: ['MID', 'SUPPORT'],
    idx: 133,
    championId: 45,
  },
  velkoz: { name: '벨코즈', chosung: 'ㅂㅋㅈ', positions: ['SUPPORT'], idx: 134, championId: 161 },
  vi: { name: '바이', chosung: 'ㅂㅇ', positions: ['JUNGLE'], idx: 135, championId: 254 },
  viego: {
    name: '비에고',
    chosung: 'ㅂㅇㄱ',
    positions: ['JUNGLE', 'MID', 'TOP'],
    idx: 136,
    championId: 234,
  },
  viktor: {
    name: '빅토르',
    chosung: 'ㅂㅌㄹ',
    positions: ['MID', 'TOP'],
    idx: 137,
    championId: 112,
  },
  vladimir: {
    name: '블라디미르',
    chosung: 'ㅂㄹㄷㅁㄹ',
    positions: ['MID', 'TOP'],
    idx: 138,
    championId: 8,
  },
  volibear: {
    name: '볼리베어',
    chosung: 'ㅂㄹㅂㅇ',
    positions: ['TOP', 'JUNGLE'],
    idx: 139,
    championId: 106,
  },
  warwick: {
    name: '워윅',
    chosung: 'ㅇㅇ',
    positions: ['JUNGLE', 'TOP'],
    idx: 140,
    championId: 19,
  },
  xayah: { name: '자야', chosung: 'ㅈㅇ', positions: ['ADC'], idx: 141, championId: 498 },
  xerath: {
    name: '제라스',
    chosung: 'ㅈㄹㅅ',
    positions: ['SUPPORT', 'MID'],
    idx: 142,
    championId: 101,
  },
  xinzhao: { name: '신짜오', chosung: 'ㅅㅉㅇ', positions: ['JUNGLE'], idx: 143, championId: 5 },
  yasuo: {
    name: '야스오',
    chosung: 'ㅇㅅㅇ',
    positions: ['MID', 'TOP', 'ADC'],
    idx: 144,
    championId: 157,
  },
  yone: { name: '요네', chosung: 'ㅇㄴ', positions: ['MID', 'TOP'], idx: 145, championId: 777 },
  yorick: { name: '요릭', chosung: 'ㅇㄹ', positions: ['TOP', 'MID'], idx: 146, championId: 83 },
  yuumi: { name: '유미', chosung: 'ㅇㅁ', positions: ['SUPPORT'], idx: 147, championId: 350 },
  zac: {
    name: '자크',
    chosung: 'ㅈㅋ',
    positions: ['JUNGLE', 'TOP', 'SUPPORT'],
    idx: 148,
    championId: 154,
  },
  zed: { name: '제드', chosung: 'ㅈㄷ', positions: ['MID'], idx: 149, championId: 238 },
  ziggs: { name: '직스', chosung: 'ㅈㅅ', positions: [], idx: 150, championId: 115 },
  zilean: {
    name: '질리언',
    chosung: 'ㅈㄹㅇ',
    positions: ['SUPPORT', 'MID'],
    idx: 151,
    championId: 26,
  },
  zoe: { name: '조이', chosung: 'ㅈㅇ', positions: ['MID'], idx: 152, championId: 142 },
  zyra: { name: '자이라', chosung: 'ㅈㅇㄹ', positions: ['SUPPORT'], idx: 153, championId: 143 },
};

export default championsMeta;
