import { Region, Garena, Language } from '@/types/regionLanguage';

const IMAGE_BASE_PATH = '/assets/region/regionFlag-';

export const REGION_DATA: Region = {
  keys: [
    'Korea',
    'Japan',
    'North America',
    'Europe West',
    'Europe Nordic & East',
    'Oceania',
    'Brazil',
    'LAS',
    'LAN',
    'Russia',
    'Turkey',
  ],
  data: [
    { region: 'Korea', imagePath: `${IMAGE_BASE_PATH}kr` },
    { region: 'Japan', imagePath: `${IMAGE_BASE_PATH}jp` },
    { region: 'North America', imagePath: `${IMAGE_BASE_PATH}na` },
    { region: 'Europe West', imagePath: `${IMAGE_BASE_PATH}euw` },
    { region: 'Europe Nordic & East', imagePath: `${IMAGE_BASE_PATH}eune` },
    { region: 'Oceania', imagePath: `${IMAGE_BASE_PATH}oce` },
    { region: 'Brazil', imagePath: `${IMAGE_BASE_PATH}br` },
    { region: 'LAS', imagePath: `${IMAGE_BASE_PATH}las` },
    { region: 'LAN', imagePath: `${IMAGE_BASE_PATH}lan` },
    { region: 'Russia', imagePath: `${IMAGE_BASE_PATH}ru` },
    { region: 'Turkey', imagePath: `${IMAGE_BASE_PATH}tr` },
  ],
};
export const GARENA_REGION_DATA: Garena = {
  keys: ['Singapore', 'Indonesia', 'Philippines', 'Taiwan', 'Vietnam', 'Thailand'],
  data: [
    { region: 'Singapore', imagePath: `${IMAGE_BASE_PATH}sg` },
    { region: 'Indonesia', imagePath: `${IMAGE_BASE_PATH}ed` },
    { region: 'Philippines', imagePath: `${IMAGE_BASE_PATH}ph` },
    { region: 'Taiwan', imagePath: `${IMAGE_BASE_PATH}tw` },
    { region: 'Vietnam', imagePath: `${IMAGE_BASE_PATH}vn` },
    { region: 'Thailand', imagePath: `${IMAGE_BASE_PATH}th` },
  ],
};

export const Language_DATA: Language = {
  keys: [
    'ko_KR',
    'en_US',
    'ja',
    'pl',
    'fr',
    'de',
    'es',
    'nl',
    'da',
    'sv',
    'no',
    'ru',
    'hu',
    'fi',
    'tr',
    'ro',
    'pt',
    'zh_CN',
    'zh_TW',
    'sr',
    'it',
    'th_TH',
    'vi_VN',
  ],
  data: [
    { lang: 'ko_KR', name: '한국어' },
    { lang: 'en_US', name: 'English' },
    { lang: 'ja', name: '日本語' },
    { lang: 'pl', name: 'język polski' },
    { lang: 'fr', name: 'français' },
    { lang: 'de', name: 'Deutsch' },
    { lang: 'es', name: 'español' },
    { lang: 'nl', name: 'Nederlands' },
    { lang: 'da', name: 'dansk' },
    { lang: 'sv', name: 'Svenska' },
    { lang: 'no', name: 'Norsk' },
    { lang: 'ru', name: 'русский язык' },
    { lang: 'hu', name: 'magyar' },
    { lang: 'fi', name: 'suomi' },
    { lang: 'tr', name: 'Türkçe' },
    { lang: 'ro', name: 'limba română' },
    { lang: 'pt', name: 'português' },
    { lang: 'zh_CN', name: '简体中文' },
    { lang: 'zh_TW', name: '繁體中文' },
    { lang: 'sr', name: 'српски језик' },
    { lang: 'it', name: 'italiano' },
    { lang: 'th_TH', name: 'ไทย' },
    { lang: 'vi_VN', name: 'Tiếng Việt' },
  ],
};
