import { championsMeta, ChampionMeta } from './championsMeta';

export interface SearchChampionMeta extends ChampionMeta {
  keyword: string;
}

type SearchChampionType = Record<string, SearchChampionMeta | SearchChampionMeta[]>;

const en = {
  aatrox: { ...championsMeta['aatrox'], keyword: 'Aatrox' },
  ahri: { ...championsMeta['ahri'], keyword: 'Ahri' },
  akali: { ...championsMeta['akali'], keyword: 'Akali' },
  alistar: { ...championsMeta['alistar'], keyword: 'Alistar' },
  amumu: { ...championsMeta['amumu'], keyword: 'Amumu' },
  anivia: { ...championsMeta['anivia'], keyword: 'Anivia' },
  annie: { ...championsMeta['annie'], keyword: 'Annie' },
  aphelios: { ...championsMeta['aphelios'], keyword: 'Aphelios' },
  ashe: { ...championsMeta['ashe'], keyword: 'Ashe' },
  aurelionsol: { ...championsMeta['aurelionsol'], keyword: 'Aurelionsol' },
  azir: { ...championsMeta['azir'], keyword: 'Azir' },
  bard: { ...championsMeta['bard'], keyword: 'Bard' },
  blitzcrank: { ...championsMeta['blitzcrank'], keyword: 'Blitzcrank' },
  brand: { ...championsMeta['brand'], keyword: 'Brand' },
  braum: { ...championsMeta['braum'], keyword: 'Braum' },
  caitlyn: { ...championsMeta['caitlyn'], keyword: 'Caitlyn' },
  camille: { ...championsMeta['camille'], keyword: 'Camille' },
  cassiopeia: { ...championsMeta['cassiopeia'], keyword: 'Cassiopeia' },
  chogath: { ...championsMeta['chogath'], keyword: 'Chogath' },
  corki: { ...championsMeta['corki'], keyword: 'Corki' },
  darius: { ...championsMeta['darius'], keyword: 'Darius' },
  diana: { ...championsMeta['diana'], keyword: 'Diana' },
  draven: { ...championsMeta['draven'], keyword: 'Draven' },
  drmundo: { ...championsMeta['drmundo'], keyword: 'Drmundo' },
  ekko: { ...championsMeta['ekko'], keyword: 'Ekko' },
  elise: { ...championsMeta['elise'], keyword: 'Elise' },
  evelynn: { ...championsMeta['evelynn'], keyword: 'Evelynn' },
  ezreal: { ...championsMeta['ezreal'], keyword: 'Ezreal' },
  fiddlesticks: { ...championsMeta['fiddlesticks'], keyword: 'Fiddlesticks' },
  fiora: { ...championsMeta['fiora'], keyword: 'Fiora' },
  fizz: { ...championsMeta['fizz'], keyword: 'Fizz' },
  galio: { ...championsMeta['galio'], keyword: 'Galio' },
  gangplank: { ...championsMeta['gangplank'], keyword: 'Gangplank' },
  garen: { ...championsMeta['garen'], keyword: 'Garen' },
  gnar: { ...championsMeta['gnar'], keyword: 'Gnar' },
  gragas: { ...championsMeta['gragas'], keyword: 'Gragas' },
  graves: { ...championsMeta['graves'], keyword: 'Graves' },
  hecarim: { ...championsMeta['hecarim'], keyword: 'Hecarim' },
  heimerdinger: { ...championsMeta['heimerdinger'], keyword: 'Heimerdinger' },
  illaoi: { ...championsMeta['illaoi'], keyword: 'Illaoi' },
  irelia: { ...championsMeta['irelia'], keyword: 'Irelia' },
  ivern: { ...championsMeta['ivern'], keyword: 'Ivern' },
  janna: { ...championsMeta['janna'], keyword: 'Janna' },
  jarvaniv: { ...championsMeta['jarvaniv'], keyword: 'Jarvaniv' },
  jax: { ...championsMeta['jax'], keyword: 'Jax' },
  jayce: { ...championsMeta['jayce'], keyword: 'Jayce' },
  jhin: { ...championsMeta['jhin'], keyword: 'Jhin' },
  jinx: { ...championsMeta['jinx'], keyword: 'Jinx' },
  kaisa: { ...championsMeta['kaisa'], keyword: 'Kaisa' },
  kalista: { ...championsMeta['kalista'], keyword: 'Kalista' },
  karma: { ...championsMeta['karma'], keyword: 'Karma' },
  karthus: { ...championsMeta['karthus'], keyword: 'Karthus' },
  kassadin: { ...championsMeta['kassadin'], keyword: 'Kassadin' },
  katarina: { ...championsMeta['katarina'], keyword: 'Katarina' },
  kayle: { ...championsMeta['kayle'], keyword: 'Kayle' },
  kayn: { ...championsMeta['kayn'], keyword: 'Kayn' },
  kennen: { ...championsMeta['kennen'], keyword: 'Kennen' },
  khazix: { ...championsMeta['khazix'], keyword: 'Khazix' },
  kindred: { ...championsMeta['kindred'], keyword: 'Kindred' },
  kled: { ...championsMeta['kled'], keyword: 'Kled' },
  kogmaw: { ...championsMeta['kogmaw'], keyword: 'Kogmaw' },
  leblanc: { ...championsMeta['leblanc'], keyword: 'Leblanc' },
  leesin: { ...championsMeta['leesin'], keyword: 'Leesin' },
  leona: { ...championsMeta['leona'], keyword: 'Leona' },
  lillia: { ...championsMeta['lillia'], keyword: 'Lillia' },
  lissandra: { ...championsMeta['lissandra'], keyword: 'Lissandra' },
  lucian: { ...championsMeta['lucian'], keyword: 'Lucian' },
  lulu: { ...championsMeta['lulu'], keyword: 'Lulu' },
  lux: { ...championsMeta['lux'], keyword: 'Lux' },
  malphite: { ...championsMeta['malphite'], keyword: 'Malphite' },
  malzahar: { ...championsMeta['malzahar'], keyword: 'Malzahar' },
  maokai: { ...championsMeta['maokai'], keyword: 'Maokai' },
  masteryi: { ...championsMeta['masteryi'], keyword: 'Masteryi' },
  missfortune: { ...championsMeta['missfortune'], keyword: 'Missfortune' },
  monkeyking: { ...championsMeta['monkeyking'], keyword: 'Monkeyking' },
  mordekaiser: { ...championsMeta['mordekaiser'], keyword: 'Mordekaiser' },
  morgana: { ...championsMeta['morgana'], keyword: 'Morgana' },
  nami: { ...championsMeta['nami'], keyword: 'Nami' },
  nasus: { ...championsMeta['nasus'], keyword: 'Nasus' },
  nautilus: { ...championsMeta['nautilus'], keyword: 'Nautilus' },
  neeko: { ...championsMeta['neeko'], keyword: 'Neeko' },
  nidalee: { ...championsMeta['nidalee'], keyword: 'Nidalee' },
  nocturne: { ...championsMeta['nocturne'], keyword: 'Nocturne' },
  nunu: { ...championsMeta['nunu'], keyword: 'Nunu' },
  olaf: { ...championsMeta['olaf'], keyword: 'Olaf' },
  orianna: { ...championsMeta['orianna'], keyword: 'Orianna' },
  ornn: { ...championsMeta['ornn'], keyword: 'Ornn' },
  pantheon: { ...championsMeta['pantheon'], keyword: 'Pantheon' },
  poppy: { ...championsMeta['poppy'], keyword: 'Poppy' },
  pyke: { ...championsMeta['pyke'], keyword: 'Pyke' },
  qiyana: { ...championsMeta['qiyana'], keyword: 'Qiyana' },
  quinn: { ...championsMeta['quinn'], keyword: 'Quinn' },
  rakan: { ...championsMeta['rakan'], keyword: 'Rakan' },
  rammus: { ...championsMeta['rammus'], keyword: 'Rammus' },
  reksai: { ...championsMeta['reksai'], keyword: 'Reksai' },
  rell: { ...championsMeta['rell'], keyword: 'Rell' },
  renekton: { ...championsMeta['renekton'], keyword: 'Renekton' },
  rengar: { ...championsMeta['rengar'], keyword: 'Rengar' },
  riven: { ...championsMeta['riven'], keyword: 'Riven' },
  rumble: { ...championsMeta['rumble'], keyword: 'Rumble' },
  ryze: { ...championsMeta['ryze'], keyword: 'Ryze' },
  samira: { ...championsMeta['samira'], keyword: 'Samira' },
  sejuani: { ...championsMeta['sejuani'], keyword: 'Sejuani' },
  senna: { ...championsMeta['senna'], keyword: 'Senna' },
  seraphine: { ...championsMeta['seraphine'], keyword: 'Seraphine' },
  sett: { ...championsMeta['sett'], keyword: 'Sett' },
  shaco: { ...championsMeta['shaco'], keyword: 'Shaco' },
  shen: { ...championsMeta['shen'], keyword: 'Shen' },
  shyvana: { ...championsMeta['shyvana'], keyword: 'Shyvana' },
  singed: { ...championsMeta['singed'], keyword: 'Singed' },
  sion: { ...championsMeta['sion'], keyword: 'Sion' },
  sivir: { ...championsMeta['sivir'], keyword: 'Sivir' },
  skarner: { ...championsMeta['skarner'], keyword: 'Skarner' },
  sona: { ...championsMeta['sona'], keyword: 'Sona' },
  soraka: { ...championsMeta['soraka'], keyword: 'Soraka' },
  swain: { ...championsMeta['swain'], keyword: 'Swain' },
  sylas: { ...championsMeta['sylas'], keyword: 'Sylas' },
  syndra: { ...championsMeta['syndra'], keyword: 'Syndra' },
  tahmkench: { ...championsMeta['tahmkench'], keyword: 'Tahmkench' },
  taliyah: { ...championsMeta['taliyah'], keyword: 'Taliyah' },
  talon: { ...championsMeta['talon'], keyword: 'Talon' },
  taric: { ...championsMeta['taric'], keyword: 'Taric' },
  teemo: { ...championsMeta['teemo'], keyword: 'Teemo' },
  thresh: { ...championsMeta['thresh'], keyword: 'Thresh' },
  tristana: { ...championsMeta['tristana'], keyword: 'Tristana' },
  trundle: { ...championsMeta['trundle'], keyword: 'Trundle' },
  tryndamere: { ...championsMeta['tryndamere'], keyword: 'Tryndamere' },
  twistedfate: { ...championsMeta['twistedfate'], keyword: 'Twistedfate' },
  twitch: { ...championsMeta['twitch'], keyword: 'Twitch' },
  udyr: { ...championsMeta['udyr'], keyword: 'Udyr' },
  urgot: { ...championsMeta['urgot'], keyword: 'Urgot' },
  varus: { ...championsMeta['varus'], keyword: 'Varus' },
  vayne: { ...championsMeta['vayne'], keyword: 'Vayne' },
  veigar: { ...championsMeta['veigar'], keyword: 'Veigar' },
  velkoz: { ...championsMeta['velkoz'], keyword: 'Velkoz' },
  vi: { ...championsMeta['vi'], keyword: 'Vi' },
  viego: { ...championsMeta['viego'], keyword: 'Viego' },
  viktor: { ...championsMeta['viktor'], keyword: 'Viktor' },
  vladimir: { ...championsMeta['vladimir'], keyword: 'Vladimir' },
  volibear: { ...championsMeta['volibear'], keyword: 'Volibear' },
  warwick: { ...championsMeta['warwick'], keyword: 'Warwick' },
  xayah: { ...championsMeta['xayah'], keyword: 'Xayah' },
  xerath: { ...championsMeta['xerath'], keyword: 'Xerath' },
  xinzhao: { ...championsMeta['xinzhao'], keyword: 'Xinzhao' },
  yasuo: { ...championsMeta['yasuo'], keyword: 'Yasuo' },
  yone: { ...championsMeta['yone'], keyword: 'Yone' },
  yorick: { ...championsMeta['yorick'], keyword: 'Yorick' },
  yuumi: { ...championsMeta['yuumi'], keyword: 'Yuumi' },
  zac: { ...championsMeta['zac'], keyword: 'Zac' },
  zed: { ...championsMeta['zed'], keyword: 'Zed' },
  ziggs: { ...championsMeta['ziggs'], keyword: 'Ziggs' },
  zilean: { ...championsMeta['zilean'], keyword: 'Zilean' },
  zoe: { ...championsMeta['zoe'], keyword: 'Zoe' },
  zyra: { ...championsMeta['zyra'], keyword: 'Zyra' },
};

const kr = {
  아트록스: { ...championsMeta['aatrox'], keyword: 'Aatrox' },
  아리: { ...championsMeta['ahri'], keyword: 'Ahri' },
  아칼리: { ...championsMeta['akali'], keyword: 'Akali' },
  알리스타: { ...championsMeta['alistar'], keyword: 'Alistar' },
  아무무: { ...championsMeta['amumu'], keyword: 'Amumu' },
  애니비아: { ...championsMeta['anivia'], keyword: 'Anivia' },
  애니: { ...championsMeta['annie'], keyword: 'Annie' },
  아펠리오스: { ...championsMeta['aphelios'], keyword: 'Aphelios' },
  애쉬: { ...championsMeta['ashe'], keyword: 'Ashe' },
  아우렐리온솔: { ...championsMeta['aurelionsol'], keyword: 'Aurelionsol' },
  아지르: { ...championsMeta['azir'], keyword: 'Azir' },
  바드: { ...championsMeta['bard'], keyword: 'Bard' },
  블리츠크랭크: { ...championsMeta['blitzcrank'], keyword: 'Blitzcrank' },
  브랜드: { ...championsMeta['brand'], keyword: 'Brand' },
  브라움: { ...championsMeta['braum'], keyword: 'Braum' },
  케이틀린: { ...championsMeta['caitlyn'], keyword: 'Caitlyn' },
  카밀: { ...championsMeta['camille'], keyword: 'Camille' },
  카시오페아: { ...championsMeta['cassiopeia'], keyword: 'Cassiopeia' },
  초가스: { ...championsMeta['chogath'], keyword: 'Chogath' },
  코르키: { ...championsMeta['corki'], keyword: 'Corki' },
  다리우스: { ...championsMeta['darius'], keyword: 'Darius' },
  다이애나: { ...championsMeta['diana'], keyword: 'Diana' },
  드레이븐: { ...championsMeta['draven'], keyword: 'Draven' },
  문도박사: { ...championsMeta['drmundo'], keyword: 'Drmundo' },
  에코: { ...championsMeta['ekko'], keyword: 'Ekko' },
  엘리스: { ...championsMeta['elise'], keyword: 'Elise' },
  이블린: { ...championsMeta['evelynn'], keyword: 'Evelynn' },
  이즈리얼: { ...championsMeta['ezreal'], keyword: 'Ezreal' },
  피들스틱: { ...championsMeta['fiddlesticks'], keyword: 'Fiddlesticks' },
  피오라: { ...championsMeta['fiora'], keyword: 'Fiora' },
  피즈: { ...championsMeta['fizz'], keyword: 'Fizz' },
  갈리오: { ...championsMeta['galio'], keyword: 'Galio' },
  갱플랭크: { ...championsMeta['gangplank'], keyword: 'Gangplank' },
  가렌: { ...championsMeta['garen'], keyword: 'Garen' },
  나르: { ...championsMeta['gnar'], keyword: 'Gnar' },
  그라가스: { ...championsMeta['gragas'], keyword: 'Gragas' },
  그레이브즈: { ...championsMeta['graves'], keyword: 'Graves' },
  헤카림: { ...championsMeta['hecarim'], keyword: 'Hecarim' },
  하이머딩거: { ...championsMeta['heimerdinger'], keyword: 'Heimerdinger' },
  일라오이: { ...championsMeta['illaoi'], keyword: 'Illaoi' },
  이렐리아: { ...championsMeta['irelia'], keyword: 'Irelia' },
  아이번: { ...championsMeta['ivern'], keyword: 'Ivern' },
  잔나: { ...championsMeta['janna'], keyword: 'Janna' },
  자르반4세: { ...championsMeta['jarvaniv'], keyword: 'Jarvaniv' },
  잭스: { ...championsMeta['jax'], keyword: 'Jax' },
  제이스: { ...championsMeta['jayce'], keyword: 'Jayce' },
  진: { ...championsMeta['jhin'], keyword: 'Jhin' },
  징크스: { ...championsMeta['jinx'], keyword: 'Jinx' },
  카이사: { ...championsMeta['kaisa'], keyword: 'Kaisa' },
  칼리스타: { ...championsMeta['kalista'], keyword: 'Kalista' },
  카르마: { ...championsMeta['karma'], keyword: 'Karma' },
  카서스: { ...championsMeta['karthus'], keyword: 'Karthus' },
  카사딘: { ...championsMeta['kassadin'], keyword: 'Kassadin' },
  카타리나: { ...championsMeta['katarina'], keyword: 'Katarina' },
  케일: { ...championsMeta['kayle'], keyword: 'Kayle' },
  케인: { ...championsMeta['kayn'], keyword: 'Kayn' },
  케넨: { ...championsMeta['kennen'], keyword: 'Kennen' },
  카직스: { ...championsMeta['khazix'], keyword: 'Khazix' },
  킨드레드: { ...championsMeta['kindred'], keyword: 'Kindred' },
  클레드: { ...championsMeta['kled'], keyword: 'Kled' },
  코그모: { ...championsMeta['kogmaw'], keyword: 'Kogmaw' },
  르블랑: { ...championsMeta['leblanc'], keyword: 'Leblanc' },
  리신: { ...championsMeta['leesin'], keyword: 'Leesin' },
  레오나: { ...championsMeta['leona'], keyword: 'Leona' },
  릴리아: { ...championsMeta['lillia'], keyword: 'Lillia' },
  리산드라: { ...championsMeta['lissandra'], keyword: 'Lissandra' },
  루시안: { ...championsMeta['lucian'], keyword: 'Lucian' },
  룰루: { ...championsMeta['lulu'], keyword: 'Lulu' },
  럭스: { ...championsMeta['lux'], keyword: 'Lux' },
  말파이트: { ...championsMeta['malphite'], keyword: 'Malphite' },
  말자하: { ...championsMeta['malzahar'], keyword: 'Malzahar' },
  마오카이: { ...championsMeta['maokai'], keyword: 'Maokai' },
  마스터이: { ...championsMeta['masteryi'], keyword: 'Masteryi' },
  미스포츈: { ...championsMeta['missfortune'], keyword: 'Missfortune' },
  오공: { ...championsMeta['monkeyking'], keyword: 'Monkeyking' },
  모데카이저: { ...championsMeta['mordekaiser'], keyword: 'Mordekaiser' },
  모르가나: { ...championsMeta['morgana'], keyword: 'Morgana' },
  나미: { ...championsMeta['nami'], keyword: 'Nami' },
  나서스: { ...championsMeta['nasus'], keyword: 'Nasus' },
  노틸러스: { ...championsMeta['nautilus'], keyword: 'Nautilus' },
  니코: { ...championsMeta['neeko'], keyword: 'Neeko' },
  니달리: { ...championsMeta['nidalee'], keyword: 'Nidalee' },
  녹턴: { ...championsMeta['nocturne'], keyword: 'Nocturne' },
  누누와윌럼프: { ...championsMeta['nunu'], keyword: 'Nunu' },
  올라프: { ...championsMeta['olaf'], keyword: 'Olaf' },
  오리아나: { ...championsMeta['orianna'], keyword: 'Orianna' },
  오른: { ...championsMeta['ornn'], keyword: 'Ornn' },
  판테온: { ...championsMeta['pantheon'], keyword: 'Pantheon' },
  뽀삐: { ...championsMeta['poppy'], keyword: 'Poppy' },
  파이크: { ...championsMeta['pyke'], keyword: 'Pyke' },
  키아나: { ...championsMeta['qiyana'], keyword: 'Qiyana' },
  퀸: { ...championsMeta['quinn'], keyword: 'Quinn' },
  라칸: { ...championsMeta['rakan'], keyword: 'Rakan' },
  람머스: { ...championsMeta['rammus'], keyword: 'Rammus' },
  렉사이: { ...championsMeta['reksai'], keyword: 'Reksai' },
  렐: { ...championsMeta['rell'], keyword: 'Rell' },
  레넥톤: { ...championsMeta['renekton'], keyword: 'Renekton' },
  렝가: { ...championsMeta['rengar'], keyword: 'Rengar' },
  리븐: { ...championsMeta['riven'], keyword: 'Riven' },
  럼블: { ...championsMeta['rumble'], keyword: 'Rumble' },
  라이즈: { ...championsMeta['ryze'], keyword: 'Ryze' },
  사미라: { ...championsMeta['samira'], keyword: 'Samira' },
  세주아니: { ...championsMeta['sejuani'], keyword: 'Sejuani' },
  세나: { ...championsMeta['senna'], keyword: 'Senna' },
  세라핀: { ...championsMeta['seraphine'], keyword: 'Seraphine' },
  세트: { ...championsMeta['sett'], keyword: 'Sett' },
  샤코: { ...championsMeta['shaco'], keyword: 'Shaco' },
  쉔: { ...championsMeta['shen'], keyword: 'Shen' },
  쉬바나: { ...championsMeta['shyvana'], keyword: 'Shyvana' },
  신지드: { ...championsMeta['singed'], keyword: 'Singed' },
  사이온: { ...championsMeta['sion'], keyword: 'Sion' },
  시비르: { ...championsMeta['sivir'], keyword: 'Sivir' },
  스카너: { ...championsMeta['skarner'], keyword: 'Skarner' },
  소나: { ...championsMeta['sona'], keyword: 'Sona' },
  소라카: { ...championsMeta['soraka'], keyword: 'Soraka' },
  스웨인: { ...championsMeta['swain'], keyword: 'Swain' },
  사일러스: { ...championsMeta['sylas'], keyword: 'Sylas' },
  신드라: { ...championsMeta['syndra'], keyword: 'Syndra' },
  탐켄치: { ...championsMeta['tahmkench'], keyword: 'Tahmkench' },
  탈리야: { ...championsMeta['taliyah'], keyword: 'Taliyah' },
  탈론: { ...championsMeta['talon'], keyword: 'Talon' },
  타릭: { ...championsMeta['taric'], keyword: 'Taric' },
  티모: { ...championsMeta['teemo'], keyword: 'Teemo' },
  쓰레쉬: { ...championsMeta['thresh'], keyword: 'Thresh' },
  트리스타나: { ...championsMeta['tristana'], keyword: 'Tristana' },
  트런들: { ...championsMeta['trundle'], keyword: 'Trundle' },
  트린다미어: { ...championsMeta['tryndamere'], keyword: 'Tryndamere' },
  트위스티드페이트: { ...championsMeta['twistedfate'], keyword: 'Twistedfate' },
  트위치: { ...championsMeta['twitch'], keyword: 'Twitch' },
  우디르: { ...championsMeta['udyr'], keyword: 'Udyr' },
  우르곳: { ...championsMeta['urgot'], keyword: 'Urgot' },
  바루스: { ...championsMeta['varus'], keyword: 'Varus' },
  베인: { ...championsMeta['vayne'], keyword: 'Vayne' },
  베이가: { ...championsMeta['veigar'], keyword: 'Veigar' },
  벨코즈: { ...championsMeta['velkoz'], keyword: 'Velkoz' },
  바이: { ...championsMeta['vi'], keyword: 'Vi' },
  비에고: { ...championsMeta['viego'], keyword: 'Viego' },
  빅토르: { ...championsMeta['viktor'], keyword: 'Viktor' },
  블라디미르: { ...championsMeta['vladimir'], keyword: 'Vladimir' },
  볼리베어: { ...championsMeta['volibear'], keyword: 'Volibear' },
  워윅: { ...championsMeta['warwick'], keyword: 'Warwick' },
  자야: { ...championsMeta['xayah'], keyword: 'Xayah' },
  제라스: { ...championsMeta['xerath'], keyword: 'Xerath' },
  신짜오: { ...championsMeta['xinzhao'], keyword: 'Xinzhao' },
  야스오: { ...championsMeta['yasuo'], keyword: 'Yasuo' },
  요네: { ...championsMeta['yone'], keyword: 'Yone' },
  요릭: { ...championsMeta['yorick'], keyword: 'Yorick' },
  유미: { ...championsMeta['yuumi'], keyword: 'Yuumi' },
  자크: { ...championsMeta['zac'], keyword: 'Zac' },
  제드: { ...championsMeta['zed'], keyword: 'Zed' },
  직스: { ...championsMeta['ziggs'], keyword: 'Ziggs' },
  질리언: { ...championsMeta['zilean'], keyword: 'Zilean' },
  조이: { ...championsMeta['zoe'], keyword: 'Zoe' },
  자이라: { ...championsMeta['zyra'], keyword: 'Zyra' },
};

const krInitial = {
  ㅇㅌㄹㅅ: { ...championsMeta['aatrox'], keyword: 'Aatrox' },
  ㅇㄹ: [
    { ...championsMeta['ahri'], keyword: 'Ahri' },
    { ...championsMeta['ornn'], keyword: 'Ornn' },
    { ...championsMeta['yorick'], keyword: 'Yorick' },
  ],
  ㅇㅋㄹ: { ...championsMeta['akali'], keyword: 'Akali' },
  ㅇㄹㅅㅌ: { ...championsMeta['alistar'], keyword: 'Alistar' },
  ㅇㅁㅁ: { ...championsMeta['amumu'], keyword: 'Amumu' },
  ㅇㄴㅂㅇ: { ...championsMeta['anivia'], keyword: 'Anivia' },
  ㅇㄴ: [
    { ...championsMeta['annie'], keyword: 'Annie' },
    { ...championsMeta['yone'], keyword: 'Yone' },
  ],
  ㅇㅍㄹㅇㅅ: { ...championsMeta['aphelios'], keyword: 'Aphelios' },
  ㅇㅅ: { ...championsMeta['ashe'], keyword: 'Ashe' },
  ㅇㅇㄹㄹㅇㅅ: { ...championsMeta['aurelionsol'], keyword: 'Aurelionsol' },
  ㅇㅈㄹ: { ...championsMeta['azir'], keyword: 'Azir' },
  ㅂㄷ: { ...championsMeta['bard'], keyword: 'Bard' },
  ㅂㄹㅊㅋㄹㅋ: { ...championsMeta['blitzcrank'], keyword: 'Blitzcrank' },
  ㅂㄹㄷ: { ...championsMeta['brand'], keyword: 'Brand' },
  ㅂㄹㅇ: { ...championsMeta['braum'], keyword: 'Braum' },
  ㅋㅇㅌㄹ: { ...championsMeta['caitlyn'], keyword: 'Caitlyn' },
  ㅋㅁ: { ...championsMeta['camille'], keyword: 'Camille' },
  ㅋㅅㅇㅍㅇ: { ...championsMeta['cassiopeia'], keyword: 'Cassiopeia' },
  ㅊㄱㅅ: { ...championsMeta['chogath'], keyword: 'Chogath' },
  ㅋㄹㅋ: { ...championsMeta['corki'], keyword: 'Corki' },
  ㄷㄹㅇㅅ: { ...championsMeta['darius'], keyword: 'Darius' },
  ㄷㅇㅇㄴ: { ...championsMeta['diana'], keyword: 'Diana' },
  ㄷㄹㅇㅂ: { ...championsMeta['draven'], keyword: 'Draven' },
  ㅁㄷㅂㅅ: { ...championsMeta['drmundo'], keyword: 'Drmundo' },
  ㅇㅋ: { ...championsMeta['ekko'], keyword: 'Ekko' },
  ㅇㄹㅅ: { ...championsMeta['elise'], keyword: 'Elise' },
  ㅇㅂㄹ: { ...championsMeta['evelynn'], keyword: 'Evelynn' },
  ㅇㅈㄹㅇ: { ...championsMeta['ezreal'], keyword: 'Ezreal' },
  ㅍㄷㅅㅌ: { ...championsMeta['fiddlesticks'], keyword: 'Fiddlesticks' },
  ㅍㅇㄹ: { ...championsMeta['fiora'], keyword: 'Fiora' },
  ㅍㅈ: { ...championsMeta['fizz'], keyword: 'Fizz' },
  ㄱㄹㅇ: { ...championsMeta['galio'], keyword: 'Galio' },
  ㄱㅍㄹㅋ: { ...championsMeta['gangplank'], keyword: 'Gangplank' },
  ㄱㄹ: { ...championsMeta['garen'], keyword: 'Garen' },
  ㄴㄹ: { ...championsMeta['gnar'], keyword: 'Gnar' },
  ㄱㄹㄱㅅ: { ...championsMeta['gragas'], keyword: 'Gragas' },
  ㄱㄹㅇㅂㅈ: { ...championsMeta['graves'], keyword: 'Graves' },
  ㅎㅋㄹ: { ...championsMeta['hecarim'], keyword: 'Hecarim' },
  ㅎㅇㅁㄷㄱ: { ...championsMeta['heimerdinger'], keyword: 'Heimerdinger' },
  ㅇㄹㅇㅇ: { ...championsMeta['illaoi'], keyword: 'Illaoi' },
  ㅇㄹㄹㅇ: { ...championsMeta['irelia'], keyword: 'Irelia' },
  ㅇㅇㅂ: { ...championsMeta['ivern'], keyword: 'Ivern' },
  ㅈㄴ: { ...championsMeta['janna'], keyword: 'Janna' },
  ㅈㄹㅂ4ㅅ: { ...championsMeta['jarvaniv'], keyword: 'Jarvaniv' },
  ㅈㅅ: [
    { ...championsMeta['jax'], keyword: 'Jax' },
    { ...championsMeta['ziggs'], keyword: 'Ziggs' },
  ],
  ㅈㅇㅅ: { ...championsMeta['jayce'], keyword: 'Jayce' },
  ㅈ: { ...championsMeta['jhin'], keyword: 'Jhin' },
  ㅈㅋㅅ: { ...championsMeta['jinx'], keyword: 'Jinx' },
  ㅋㅇㅅ: { ...championsMeta['kaisa'], keyword: 'Kaisa' },
  ㅋㄹㅅㅌ: { ...championsMeta['kalista'], keyword: 'Kalista' },
  ㅋㄹㅁ: { ...championsMeta['karma'], keyword: 'Karma' },
  ㅋㅅㅅ: { ...championsMeta['karthus'], keyword: 'Karthus' },
  ㅋㅅㄷ: { ...championsMeta['kassadin'], keyword: 'Kassadin' },
  ㅋㅌㄹㄴ: { ...championsMeta['katarina'], keyword: 'Katarina' },
  ㅋㅇ: [
    { ...championsMeta['kayle'], keyword: 'Kayle' },
    { ...championsMeta['kayn'], keyword: 'Kayn' },
  ],
  ㅋㄴ: { ...championsMeta['kennen'], keyword: 'Kennen' },
  ㅋㅈㅅ: { ...championsMeta['khazix'], keyword: 'Khazix' },
  ㅋㄷㄹㄷ: { ...championsMeta['kindred'], keyword: 'Kindred' },
  ㅋㄹㄷ: { ...championsMeta['kled'], keyword: 'Kled' },
  ㅋㄱㅁ: { ...championsMeta['kogmaw'], keyword: 'Kogmaw' },
  ㄹㅂㄹ: { ...championsMeta['leblanc'], keyword: 'Leblanc' },
  ㄹㅅ: [
    { ...championsMeta['leesin'], keyword: 'Leesin' },
    { ...championsMeta['lux'], keyword: 'Lux' },
  ],
  ㄹㅇㄴ: { ...championsMeta['leona'], keyword: 'Leona' },
  ㄹㄹㅇ: { ...championsMeta['lillia'], keyword: 'Lillia' },
  ㄹㅅㄷㄹ: { ...championsMeta['lissandra'], keyword: 'Lissandra' },
  ㄹㅅㅇ: [
    { ...championsMeta['lucian'], keyword: 'Lucian' },
    { ...championsMeta['reksai'], keyword: 'Reksai' },
  ],
  ㄹㄹ: { ...championsMeta['lulu'], keyword: 'Lulu' },
  ㅁㅍㅇㅌ: { ...championsMeta['malphite'], keyword: 'Malphite' },
  ㅁㅈㅎ: { ...championsMeta['malzahar'], keyword: 'Malzahar' },
  ㅁㅇㅋㅇ: { ...championsMeta['maokai'], keyword: 'Maokai' },
  ㅁㅅㅌㅇ: { ...championsMeta['masteryi'], keyword: 'Masteryi' },
  ㅁㅅㅍㅊ: { ...championsMeta['missfortune'], keyword: 'Missfortune' },
  ㅇㄱ: { ...championsMeta['monkeyking'], keyword: 'Monkeyking' },
  ㅁㄷㅋㅇㅈ: { ...championsMeta['mordekaiser'], keyword: 'Mordekaiser' },
  ㅁㄹㄱㄴ: { ...championsMeta['morgana'], keyword: 'Morgana' },
  ㄴㅁ: { ...championsMeta['nami'], keyword: 'Nami' },
  ㄴㅅㅅ: { ...championsMeta['nasus'], keyword: 'Nasus' },
  ㄴㅌㄹㅅ: { ...championsMeta['nautilus'], keyword: 'Nautilus' },
  ㄴㅋ: { ...championsMeta['neeko'], keyword: 'Neeko' },
  ㄴㄷㄹ: { ...championsMeta['nidalee'], keyword: 'Nidalee' },
  ㄴㅌ: { ...championsMeta['nocturne'], keyword: 'Nocturne' },
  ㄴㄴㅇㅇㄹㅍ: { ...championsMeta['nunu'], keyword: 'Nunu' },
  ㅇㄹㅍ: { ...championsMeta['olaf'], keyword: 'Olaf' },
  ㅇㄹㅇㄴ: { ...championsMeta['orianna'], keyword: 'Orianna' },
  ㅍㅌㅇ: { ...championsMeta['pantheon'], keyword: 'Pantheon' },
  ㅃㅃ: { ...championsMeta['poppy'], keyword: 'Poppy' },
  ㅍㅇㅋ: { ...championsMeta['pyke'], keyword: 'Pyke' },
  ㅋㅇㄴ: { ...championsMeta['qiyana'], keyword: 'Qiyana' },
  ㅋ: { ...championsMeta['quinn'], keyword: 'Quinn' },
  ㄹㅋ: { ...championsMeta['rakan'], keyword: 'Rakan' },
  ㄹㅁㅅ: { ...championsMeta['rammus'], keyword: 'Rammus' },
  ㄹ: { ...championsMeta['rell'], keyword: 'Rell' },
  ㄹㄴㅌ: { ...championsMeta['renekton'], keyword: 'Renekton' },
  ㄹㄱ: { ...championsMeta['rengar'], keyword: 'Rengar' },
  ㄹㅂ: [
    { ...championsMeta['riven'], keyword: 'Riven' },
    { ...championsMeta['rumble'], keyword: 'Rumble' },
  ],
  ㄹㅇㅈ: { ...championsMeta['ryze'], keyword: 'Ryze' },
  ㅅㅁㄹ: { ...championsMeta['samira'], keyword: 'Samira' },
  ㅅㅈㅇㄴ: { ...championsMeta['sejuani'], keyword: 'Sejuani' },
  ㅅㄴ: [
    { ...championsMeta['senna'], keyword: 'Senna' },
    { ...championsMeta['sona'], keyword: 'Sona' },
  ],
  ㅅㄹㅍ: { ...championsMeta['seraphine'], keyword: 'Seraphine' },
  ㅅㅌ: { ...championsMeta['sett'], keyword: 'Sett' },
  ㅅㅋ: { ...championsMeta['shaco'], keyword: 'Shaco' },
  ㅅ: { ...championsMeta['shen'], keyword: 'Shen' },
  ㅅㅂㄴ: { ...championsMeta['shyvana'], keyword: 'Shyvana' },
  ㅅㅈㄷ: { ...championsMeta['singed'], keyword: 'Singed' },
  ㅅㅇㅇ: [
    { ...championsMeta['sion'], keyword: 'Sion' },
    { ...championsMeta['swain'], keyword: 'Swain' },
  ],
  ㅅㅂㄹ: { ...championsMeta['sivir'], keyword: 'Sivir' },
  ㅅㅋㄴ: { ...championsMeta['skarner'], keyword: 'Skarner' },
  ㅅㄹㅋ: { ...championsMeta['soraka'], keyword: 'Soraka' },
  ㅅㅇㄹㅅ: { ...championsMeta['sylas'], keyword: 'Sylas' },
  ㅅㄷㄹ: { ...championsMeta['syndra'], keyword: 'Syndra' },
  ㅌㅋㅊ: { ...championsMeta['tahmkench'], keyword: 'Tahmkench' },
  ㅌㄹㅇ: { ...championsMeta['taliyah'], keyword: 'Taliyah' },
  ㅌㄹ: [
    { ...championsMeta['talon'], keyword: 'Talon' },
    { ...championsMeta['taric'], keyword: 'Taric' },
  ],
  ㅌㅁ: { ...championsMeta['teemo'], keyword: 'Teemo' },
  ㅆㄹㅅ: { ...championsMeta['thresh'], keyword: 'Thresh' },
  ㅌㄹㅅㅌㄴ: { ...championsMeta['tristana'], keyword: 'Tristana' },
  ㅌㄹㄷ: { ...championsMeta['trundle'], keyword: 'Trundle' },
  ㅌㄹㄷㅁㅇ: { ...championsMeta['tryndamere'], keyword: 'Tryndamere' },
  ㅌㅇㅅㅌㄷㅍㅇㅌ: { ...championsMeta['twistedfate'], keyword: 'Twistedfate' },
  ㅌㅇㅊ: { ...championsMeta['twitch'], keyword: 'Twitch' },
  ㅇㄷㄹ: { ...championsMeta['udyr'], keyword: 'Udyr' },
  ㅇㄹㄱ: { ...championsMeta['urgot'], keyword: 'Urgot' },
  ㅂㄹㅅ: { ...championsMeta['varus'], keyword: 'Varus' },
  ㅂㅇ: [
    { ...championsMeta['vayne'], keyword: 'Vayne' },
    { ...championsMeta['vi'], keyword: 'Vi' },
  ],
  ㅂㅇㄱ: [
    { ...championsMeta['veigar'], keyword: 'Veigar' },
    { ...championsMeta['viego'], keyword: 'Viego' },
  ],
  ㅂㅋㅈ: { ...championsMeta['velkoz'], keyword: 'Velkoz' },
  ㅂㅌㄹ: { ...championsMeta['viktor'], keyword: 'Viktor' },
  ㅂㄹㄷㅁㄹ: { ...championsMeta['vladimir'], keyword: 'Vladimir' },
  ㅂㄹㅂㅇ: { ...championsMeta['volibear'], keyword: 'Volibear' },
  ㅇㅇ: { ...championsMeta['warwick'], keyword: 'Warwick' },
  ㅈㅇ: [
    { ...championsMeta['xayah'], keyword: 'Xayah' },
    { ...championsMeta['zoe'], keyword: 'Zoe' },
  ],
  ㅈㄹㅅ: { ...championsMeta['xerath'], keyword: 'Xerath' },
  ㅅㅉㅇ: { ...championsMeta['xinzhao'], keyword: 'Xinzhao' },
  ㅇㅅㅇ: { ...championsMeta['yasuo'], keyword: 'Yasuo' },
  ㅇㅁ: { ...championsMeta['yuumi'], keyword: 'Yuumi' },
  ㅈㅋ: { ...championsMeta['zac'], keyword: 'Zac' },
  ㅈㄷ: { ...championsMeta['zed'], keyword: 'Zed' },
  ㅈㄹㅇ: { ...championsMeta['zilean'], keyword: 'Zilean' },
  ㅈㅇㄹ: { ...championsMeta['zyra'], keyword: 'Zyra' },
};

export const keywords: SearchChampionType = {
  ...en,
  ...kr,
  ...krInitial,
};
